kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: build on main
  image: golang
  commands:
  - apt-get update
  - apt-get install -y ca-certificates curl gnupg
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor --no-tty --yes -o /etc/apt/keyrings/nodesource.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
  - apt-get install -y nodejs
  - npm install -g cdk8s-cli
  - cdk8s import
  - git diff
  - git checkout cdk8s.yaml
  - cdk8s synth

- name: prepare generated
  image: golang
  commands:
  - git fetch origin +refs/heads/generated
  - git checkout generated
  - git rm generated/*.yaml
  - mkdir -p generated
  - touch generated/.gitkeep
  - cp -Rp dist/* generated/
  - find generated

- name: git-push
  image: appleboy/drone-git-push
  settings:
    local_branch: generated
    branch: generated
    remote: ssh://git@git.mkz.me/mycroft/k8s-home.git
    force: false
    commit: true
    commit_message: Update generated configuration
    ssh_key:
      from_secret: ssh_key_drone

- name: github-mirror-main
  image: appleboy/drone-git-push
  settings:
    local_branch: main
    branch: main
    remote: ssh://git@github.com/mycroft/k8s-home.git
    force: false
    commit: false
    ssh_key:
      from_secret: ssh_key_drone

- name: github-mirror-generated
  image: appleboy/drone-git-push
  settings:
    local_branch: generated
    branch: generated
    remote: ssh://git@github.com/mycroft/k8s-home.git
    force: false
    commit: false
    ssh_key:
      from_secret: ssh_key_drone
