kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: build on main
  image: golang
  commands:
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g cdk8s-cli
  - cdk8s import
  - cdk8s synth

- name: prepare generated
  image: golang
  commands:
  - git fetch origin +refs/heads/generated
  - git checkout generated
  - git rm generated/*.yaml
  - mkdir -p generated
  - touch generated/.gitkeep
  - cp -Rp dist/* generated/
  - find generated

- name: git-push
  image: appleboy/drone-git-push
  settings:
    local_branch: generated
    branch: generated
    remote: ssh://git@git.mkz.me/mycroft/k8s-home.git
    force: false
    commit: true
    commit_message: Update generated configuration
    ssh_key:
      from_secret: ssh_key
