kind: pipeline
type: docker
name: default

steps:
- name: build on main
  when:
    branch: main
    event: push
  image: golang
  commands:
  - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - npm install -g cdk8s-cli
  - cdk8s import
  - cdk8s synth

- name: prepare generated
  when:
    branch: main
    event: push
  image: golang
  commands:
  - git fetch origin +refs/heads/generated
  - git checkout generated
  - git rm -r generated/
  - touch generated/.gitkeep
  - cp -Rp dist/ generated/

- name: git-push
  when:
    branch: main
    event: push
  image: appleboy/drone-git-push
  settings:
    local_branch: generated
    branch: generated
    remote: git@git.mkz.me:mycroft/k8s-home.git
    force: false
    commit: true
    commit_message: Update generated configuration
    ssh_key:
      from_secret: ssh_key
