run:
  concurrency: 4
  timeout: 5m

linters:
  disable-all: true
  enable:
  - errcheck
  - gofmt
  - gosec
  - revive

linters-settings:
  errcheck:
    ignore: ''

issues:
  exclude-dirs:
    - imports
  exclude:
    - G107