[tools]
golang = "1.26.1"
golangci-lint = { version = "2.12.2", depends = "golang" }
node = "22"
"npm:cdk8s-cli" = { version = "2.206.10", depends = "node" }

[tasks.import]
description = "cdk8s import"
run = "cdk8s import"

[tasks.synth]
description = "cdk8s synth"
run = "cdk8s synth"

[tasks.build]
description = "Build the k8s-home binary"
run = "go build -o . ./..."
sources = ["charts/**/*", "internal/**/*", "main.go"]
outputs = ["k8s-home"]

[tasks.generate-charts]
description = "Generate k8s charts"
depends = "build"
run = "./k8s-home"
outputs = ["dist/*.k8s.yaml"]

[tasks.diff]
description = "Diff"
run = "git diff remotes/origin/generated:generated dist"

[tasks.conftest]
description = "Run conftest against generated charts"
depends = ["generate-charts"]
sources = ["dist/*.k8s.yaml"]
run = "conftest test --policy policies ./dist"

[tasks.lint]
description = "Run lint against golang code"
run = "golangci-lint run -c .golangci.yaml"

[tasks.check-versions]
description = "Find outdated helm charts & images"
depends = ["build"]
run = "./k8s-home check-versions {{arg(name='args', var=true, default='')}}"

