#!/bin/sh

set -x

script_dir=$(cd $(dirname $0); /bin/pwd)

cd ${script_dir}

VERSIONS=$(./k8s-home -check-version)
IFS="
"

for version in ${VERSIONS}
do
    echo ">>> ${version}"
    sh ./create-pr "${version}"
done