name: Build CI image

on:
  push:
    branches:
      - main
    paths:
      - "contrib/build-image/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Log in to container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: registry.mkz.me
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push CI image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: ./contrib/build-image
          file: ./contrib/build-image/Dockerfile
          pull: true
          push: true
          no-cache: true
          tags: |
            registry.mkz.me/mycroft/golang-cdk8s:latest
            registry.mkz.me/mycroft/golang-cdk8s:build-${{ gitea.run_id }}
