name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.mkz.me/mycroft/golang-cdk8s:latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build cdk8s charts
        run: |
          cdk8s import
          git diff
          git checkout cdk8s.yaml
          cdk8s synth

      - name: Prepare generated
        run: |
          git fetch origin +refs/heads/generated
          git checkout generated
          git rm generated/*.yaml
          mkdir -p generated
          touch generated/.gitkeep
          cp -Rp dist/* generated/
          find generated
