name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.mkz.me/mycroft/golang-cdk8s:latest
      pull: always

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build cdk8s charts
        run: |
          echo "Golang version:"
          go version
          echo "cdk8s version:"
          cdk8s --version
          cdk8s import
          git diff
          git checkout cdk8s.yaml
          cdk8s synth

      - name: Push to generated branch
        run: |
          git config user.name "mycroft"
          git config user.email "pm@mkz.me"
          git fetch origin +refs/heads/generated
          git checkout generated
          git rm generated/*.yaml
          cp -Rp dist/* generated/
          git add generated/
          git commit -m "Update generated configuration" || exit 0
          git push origin generated

  push-oci:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out generated branch
        uses: actions/checkout@v4
        with:
          ref: generated

      - name: Install flux CLI
        run: |
          curl -sL -o flux.tgz https://github.com/fluxcd/flux2/releases/download/v2.8.6/flux_2.8.6_linux_amd64.tar.gz
          tar xvfz flux.tgz

      - name: Login to container registry
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        run: |
          echo "Logging in to container registry with username ${REGISTRY_USERNAME}"
          echo "${REGISTRY_PASSWORD}" | docker login registry.mkz.me -u "${REGISTRY_USERNAME}" --password-stdin

      - name: Push OCI artifact
        run: |
          ./flux push artifact \
            oci://registry.mkz.me/k8s-home/k8s-home/manifests:${{ github.sha }} \
            --source=${{ github.server_url }}/${{ github.repository }} \
            --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)" \
            --path="./generated"

      - name: Tag as latest
        run: |
          ./flux tag  artifact \
            oci://registry.mkz.me/k8s-home/k8s-home/manifests:${{ github.sha }} \
            --tag=latest
