name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.mkz.me/mycroft/golang-cdk8s:latest
      pull: always

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build cdk8s charts
        run: |
          echo "Golang version:"
          go version
          echo "cdk8s version:"
          cdk8s --version
          cdk8s import
          git diff
          git checkout cdk8s.yaml
          cdk8s synth

      - name: Prepare generated
        run: |
          git fetch origin +refs/heads/generated
          git checkout generated
          git rm generated/*.yaml
          mkdir -p generated
          touch generated/.gitkeep
          cp -Rp dist/* generated/
          find generated

      - name: Git auto-commit changes to generated
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated configuration
          branch: generated
          commit_user_name: mycroft
          commit_user_email: pm@mkz.me
          commit_author: mycroft <pm@mkz.me>

      - name: Upload generated manifests
        uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: manifests
          path: dist/

  push-oci:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download generated manifests
        uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: manifests
          path: dist/

      - name: Install flux CLI
        run: |
          curl -sKL https://fluxcd.io/install.sh | sh
          sudo mv bin/flux /usr/local/bin/

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: registry.mkz.me
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push OCI artifact
        run: |
          flux push artifact \
            oci://registry.mkz.me/mycroft/k8s-home/manifests:${{ github.sha }} \
            --source=${{ github.server_url }}/${{ github.repository }} \
            --files=dist/*
