name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.mkz.me/mycroft/golang-cdk8s:latest
      pull: always

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build cdk8s charts
        run: |
          echo "Golang version:"
          go version
          echo "cdk8s version:"
          cdk8s --version
          cdk8s import
          git diff
          git checkout cdk8s.yaml
          cdk8s synth

      - name: Prepare generated
        run: |
          git fetch origin +refs/heads/generated
          git checkout generated
          git rm generated/*.yaml
          mkdir -p generated
          touch generated/.gitkeep
          cp -Rp dist/* generated/
          find generated

      - name: Git auto-commit changes to generated
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update generated configuration
          branch: generated
          commit_user_name: mycroft
          commit_user_email: pm@mkz.me
          commit_author: mycroft <pm@mkz.me>
