apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-builds

labels:
- includeSelectors: true
  pairs:
    build: k8s-home-tekton-cicd

resources:
- tasks/hello-world-task.yaml
- tasks/hello-world-taskrun.yaml
- tasks/goodbye-task.yaml
- pipelines/hello-world-pipeline.yaml
- pipelines/hello-world-pipelinerun.yaml
- triggers/hello-template.yaml
- triggers/hello-binding.yaml
- triggers/hello-listener.yaml
- triggers/service-account.yaml
