apiVersion: v1
kind: Namespace
metadata:
  name: alloy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-helm-val-alloy-c88c2f34
  namespace: alloy
data:
  values.yaml: |
    # https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml

    alloy:
      configMap:
        create: true
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.cluster.receiver]
          }

          loki.write "cluster" {
            endpoint {
              url = env("LOKI_URL")
            }
          }


      extraEnv:
        - name: LOKI_URL
          value: "http://loki-gateway.loki/loki/api/v1/push"

    serviceMonitor:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 6ddca48ca25d9ce1ba2240be4242cf075249c7219aeeab27c78d32cecb24d6d2
  name: alloy
  namespace: alloy
spec:
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 0.3.2
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: alloy-helm-val-alloy-c88c2f34
      valuesKey: values.yaml
