apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-helm-val-blackbox-exporter-c870357d
  namespace: monitoring
data:
  values.yaml: |
    # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml

    replicas: 1

    serviceMonitor:
      enabled: true

      selfMonitor:
        enabled: true

      targets:
      - name: hey
        url: https://hey.mkz.me/
        interval: 30s
        module: http_2xx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: b02c0d8fdfb923f2c68d29507c5872afc88d696bafee62eeaa71ed423414f106
  name: blackbox-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 9.2.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: blackbox-exporter-helm-val-blackbox-exporter-c870357d
      valuesKey: values.yaml
