apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.jetstack.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-helm-val-cert-manager-c8bc2bb8
  namespace: cert-manager
data:
  values.yaml: |
    # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: c16079d6f4db181668c7c9de10e987dce4d429b7f409b60e536c341f82253ed9
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.13.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values:
    installCRDs: "true"
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-helm-val-cert-manager-c8bc2bb8
      valuesKey: values.yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: pm+letsencrypt@mkz.me
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: pm+letsencrypt@mkz.me
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
