apiVersion: v1
kind: Namespace
metadata:
  name: dex-idp
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.dexidp.io
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    config:
      # Set it to a valid URL
      issuer: https://dex.services.mkz.me

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      # Enable at least one connector
      # See https://dexidp.io/docs/connectors/ for more options
      enablePasswordDB: true

    # The configuration is now in the secret
    configSecret:
      create: false
      name: "dex-config"

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/redirect-entry-point: "https"
        traefik.ingress.kubernetes.io/redirect-permanent: "true"

      hosts:
        - host: dex.services.mkz.me
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - dex.services.mkz.me
          secretName: dex-cert-tls

    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
metadata:
  name: dex-idp-helm-values-c8c7e322
  namespace: dex-idp
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: a0e7e0ae250448c531689445841925be290486715233eb2382bc3b9f876cba7d
  name: dex
  namespace: dex-idp
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      version: 0.12.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: dex-idp-helm-values-c8c7e322
      valuesKey: values.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dex-config
  namespace: dex-idp
spec:
  encryptedData:
    config.yaml: AgDIMrmuMJFfWPxdtE89v7ISUKbb3M11VsfqWgEPjN3HdlTg82QXskAA+EVt1D0uAunlsdImaU+8xF2dvO+Ei4sED34HvIQJe9AD6dcNp8uVrsMM3TUa2K8tS8LVT9XcGjG2J0iKMTz8fQsL/3j9WFWb7KCIwpJZxEJfI4GyhWVVbtLi4/7ImplCwW1OUNxJOn78R6Gfng3e+Q2NSiNcBnwt6kGgclLrsHoJJ5n0wE16TEeWeZBewRep+fwhRD/ijN0MYtsqNZDhue6wVODwWCee63yhpsj+UMv7/+XPqxxMLvHRITaAepqZNBs6gZGl9BWNWaEGAjfkf2EqTNnG6ubH4SZOgS910IV5MjkkLIQx5jZvKWn1eEWCLe8ECNGav7fe9m6eruyLoYoKmRO7eW6B/i0g2nK9o0yVwlMLilEILllLwHXfUEfHyN59/HTmfzVk9K/jXQlSYZnl+i6CIwW+yDyhROuJUpA8BvYATX8vQbQseu1Jw3A11uPkdHQWQvupVUQkLDIzeZzgDkYHSYQ37XepEaI38IHg6hh9i8XJ9tGPoGYhsy9YMNBLBZKfEoogwIZU3hnoKT8YHMB07fNs3ku3SGmmiENJsF3HAsKU9EvoO9EJW9B02A5Iux0qZu8nl2IUSfbXmzdXflQ4qBd1gPhIQ2WNxc5ceLCP1or1KZtmdqmxSJun2n30KYitoZW/s4+vWyuEYpM1QUw4XvlxvGnzSBKpoenkGJx9yOHRPWoZD+xjpaPt2eS9c4EeKJ8QbIsWrPZs3VWFU13Cp+y+kJwUEwQ14TLKUHx+sUIehfJheRXTxW9WEUB2HlsY9ANHay5rPbk=
