apiVersion: v1
kind: Namespace
metadata:
  name: dex-idp
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: dex-idp
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.dexidp.io
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    # https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml

    # The secrets to read & to put in dex pods
    env:
      - name: GITEA_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/gitea
            key: client_id
      - name: GITEA_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/gitea
            key: client_secret
      - name: GITEA_BASEURL
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/gitea
            key: base_url
      - name: STATIC_ADMIN_EMAIL
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/static-admin
            key: email
      - name: STATIC_ADMIN_HASH
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/static-admin
            key: hash
      - name: STATIC_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/static-admin
            key: username
      - name: STATIC_ADMIN_UUID
        valueFrom:
          secretKeyRef:
            name: secrets/namespaces/dex-idp/static-admin
            key: user_id

    # The configuration is now in the secret
    configSecret:
      create: false
      name: "dex-config"

    ingress:
      enabled: true

      annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/redirect-entry-point: "https"
        traefik.ingress.kubernetes.io/redirect-permanent: "true"

      hosts:
        - host: dex.services.mkz.me
          paths:
            - path: /
              pathType: Prefix

      tls:
        - hosts:
            - dex.services.mkz.me
          secretName: dex-cert-tls

    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
metadata:
  name: dex-idp-helm-values-c8c7e322
  namespace: dex-idp
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: fcf2a99400027cd7f38d1bbe173d0cb100c05ffc0bae3ef4f1e244b45eac7b6e
  name: dex
  namespace: dex-idp
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      version: 0.12.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: dex-idp-helm-values-c8c7e322
      valuesKey: values.yaml
---
apiVersion: v1
kind: Secret
immutable: true
metadata:
  name: dex-idp-dex-config-c8b11030
  namespace: dex-idp
stringData:
  config.yaml: |
    enablePasswordDB: true

    issuer: https://dex.services.mkz.me

    connectors:
    - type: gitea
      id: gitea
      name: Gitea
      config:
        clientID: $GITEA_CLIENT_ID
        clientSecret: $GITEA_CLIENT_SECRET
        redirectURI: https://dex.services.mkz.me/dex/callback
        baseURL: $GITEA_BASEURL

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    telemetry:
      http: 0.0.0.0:5558

    staticPasswords:
    - email: "{{ .Env.STATIC_ADMIN_EMAIL }}"
      # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
      hash: "{{ .Env.STATIC_ADMIN_HASH }}"
      username: "{{ .Env.STATIC_ADMIN_USERNAME }}"
      userID: "{{ .Env.STATIC_ADMIN_UUID }}"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-idp-es-static-admin-c88f9c6e
  namespace: dex-idp
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/dex-idp/static-admin
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: static-admin
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-idp-es-gitea-c8bff4a6
  namespace: dex-idp
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/dex-idp/gitea
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: gitea
    template:
      engineVersion: v2
      type: Opaque
