apiVersion: v1
kind: Namespace
metadata:
  name: excalidraw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-deploy-c85ccec3
  namespace: excalidraw
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: excalidraw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: excalidraw
    spec:
      containers:
        - image: excalidraw/excalidraw:latest
          name: excalidraw
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-svc-c8cb7575
  namespace: excalidraw
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: excalidraw
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: excalidraw-ingress-c89a86cb
  namespace: excalidraw
spec:
  ingressClassName: traefik
  rules:
    - host: excalidraw.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: excalidraw-svc-c8cb7575
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - excalidraw.services.mkz.me
      secretName: secret-tls-www
