apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-helm-val-external-secrets-c83d439e
  namespace: external-secrets
data:
  values.yaml: |
    # https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml

    serviceMonitor:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: b2f8324cb501ca5690dbb6dadfda795367a5d987118d709947e34696aa39bd6b
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.15.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-helm-val-external-secrets-c83d439e
      valuesKey: values.yaml
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: external-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-es-testaroo-c87eee0f
  namespace: external-secrets
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/external-secrets/testaroo
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: testaroo
    template:
      engineVersion: v2
      type: Opaque
