apiVersion: v1
kind: Namespace
metadata:
  name: freshrss
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: freshrss
  name: freshrss-freshrss-svc-c8dfddbc
  namespace: freshrss
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: freshrss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-freshrss-sts-c88554ab
  namespace: freshrss
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: freshrss
  serviceName: freshrss-freshrss-svc-c8dfddbc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: freshrss
    spec:
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: freshrss/freshrss:1.26.3
          name: freshrss
          volumeMounts:
            - mountPath: /var/www/FreshRSS/data
              name: data
            - mountPath: /var/www/FreshRSS/extensions
              name: extensions
      volumes: []
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: freshrss
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
    - metadata:
        labels:
          app.kubernetes.io/name: freshrss
        name: extensions
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: freshrss-cronjob-c8609a6c
  namespace: freshrss
spec:
  jobTemplate:
    metadata:
      namespace: freshrss
    spec:
      template:
        metadata:
          namespace: freshrss
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: statefulset.kubernetes.io/pod-name
                        operator: In
                        values:
                          - freshrss-freshrss-sts-c88554ab-0
                  topologyKey: kubernetes.io/hostname
          containers:
            - command:
                - /var/www/FreshRSS/app/actualize_script.php
              image: freshrss/freshrss:1.26.3
              name: updater
              volumeMounts:
                - mountPath: /var/www/FreshRSS/data
                  name: data
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-freshrss-freshrss-sts-c88554ab-0
  schedule: 12,42 * * * *
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: freshrss-ingress-c8de4878
  namespace: freshrss
spec:
  ingressClassName: traefik
  rules:
    - host: freshrss.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: freshrss-freshrss-svc-c8dfddbc
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - freshrss.services.mkz.me
      secretName: secret-tls-www
