apiVersion: v1
kind: Namespace
metadata:
  name: gossip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-deploy-server-c8e62b5f
  namespace: gossip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gossip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gossip
    spec:
      containers:
        - command:
            - /app/server
          env:
            - name: NATS_SERVER
              value: nats.nats:4222
            - name: DELAY
              value: "10"
          image: registry.mkz.me/test-ci/gossip:latest
          imagePullPolicy: Always
          name: gossip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-deploy-client-c87c663f
  namespace: gossip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gossip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gossip
    spec:
      containers:
        - command:
            - /app/client
          env:
            - name: NATS_SERVER
              value: nats.nats:4222
            - name: DELAY
              value: "10"
          image: registry.mkz.me/test-ci/gossip:latest
          imagePullPolicy: Always
          name: gossip
