apiVersion: v1
kind: Namespace
metadata:
  name: heimdall
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: heimdall
  name: heimdall-heimdall-svc-c8f1ed82
  namespace: heimdall
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: heimdall
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heimdall-heimdall-sts-c8f65923
  namespace: heimdall
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: heimdall
  serviceName: heimdall-heimdall-svc-c8f1ed82
  template:
    metadata:
      labels:
        app.kubernetes.io/name: heimdall
    spec:
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: linuxserver/heimdall:v2.5.6-ls228
          name: heimdall
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /var/www/FreshRSS/extensions
              name: extensions
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: heimdall
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
    - metadata:
        labels:
          app.kubernetes.io/name: heimdall
        name: extensions
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: v1
kind: Service
metadata:
  name: heimdall-svc-c82a93a6
  namespace: heimdall
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: heimdall
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: heimdall-ingress-c895cdca
  namespace: heimdall
spec:
  rules:
    - host: heimdall.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: heimdall-svc-c82a93a6
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - heimdall.services.mkz.me
      secretName: secret-tls-www
