apiVersion: v1
kind: Namespace
metadata:
  name: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-deploy-c8334d15
  namespace: hello-kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kubernetes
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: paulbouwer/hello-kubernetes:1.10.1
          name: hello-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-svc-c819e9ba
  namespace: hello-kubernetes
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: hello-kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  name: hello-kubernetes-ingress-c8762254
  namespace: hello-kubernetes
spec:
  rules:
    - host: hello-kubernetes.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: hello-kubernetes-svc-c819e9ba
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - hello-kubernetes.services.mkz.me
      secretName: secret-tls-www
