apiVersion: v1
kind: Namespace
metadata:
  name: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-deploy-c8334d15
  namespace: hello-kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kubernetes
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.10.1
          name: hello-kubernetes
