apiVersion: v1
kind: Namespace
metadata:
  name: hey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hey-deploy-c8317849
  namespace: hey
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hey
    spec:
      containers:
        - image: git.mkz.me/mycroft/hey:latest
          imagePullPolicy: Always
          name: hey
---
apiVersion: v1
kind: Service
metadata:
  name: hey-svc-c8e476b5
  namespace: hey
spec:
  ports:
    - name: http
      port: 3000
  selector:
    app.kubernetes.io/name: hey
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  name: hey-ingress-c8ad92c2
  namespace: hey
spec:
  rules:
    - host: hey.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: hey-svc-c8e476b5
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - hey.services.mkz.me
      secretName: secret-tls-www
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: hey-service-monitor-c8a2497b
  namespace: hey
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels: {}
