apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jameswynn
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://jameswynn.github.io/helm-charts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-helm-val-homepage-c8244fb9
  namespace: homepage
data:
  values.yaml: |
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.10.4

    configMaps:
      config:
        enabled: true
        data:
          config.yaml: |
            # This CM is not used at all. It is only be maintained to force deployment restart after configuration change.
            version: "67ff63f99f561eca3125cb22c17885386414939696bbe1046d34294edc753f93"

    config:
      settings:
        headerStyle: boxedWidgets
        title: Myc's homelab
        providers:
          longhorn:
            url: http://longhorn-frontend.longhorn-system
        quicklaunch:
          searchDescriptions: true
          hideInternetSearch: true
          showSearchSuggestions: true
          hideVisitURL: true
          provider: google # google, duckduckgo, bing, baidu, brave or custom
        layout:
          - System:
              header: false
              style: row
              columns: 4
          - Web Services:
              header: true
              style: row
              columns: 5
          - Web Apps:
              header: true
              style: row
              columns: 5

      bookmarks:
        - Code:
          - Github:
            - abbr: GH
              href: https://github.com/mycroft
          - Gitea:
            - abbr: GIT
              href: https://git.mkz.me/

        - Social:
          - Reddit:
            - abbr: RD
              href: https://old.reddit.com/
          - Mastodon:
            - abbr: MS
              href: https://mamot.fr/home

        - News:
          - Lobsters:
            - abbr: LB
              href: https://lobste.rs/

      services:
        - System:
          - Pi-Hole/DNS:
              href: http://10.0.0.254/admin/
              description: Pi-Hole/DNS server for blocking ads and trackers
          - Capacitor:
              href: https://capacitor.services.mkz.me/
              description: General purpose UI for Flux
          - Kubernetes-dashboard:
              href: https://kubernetes-dashboard.services.mkz.me/
              description: Web-based Kubernetes user interface
          - Authentik:
              href: https://auth.services.mkz.me/
              description: Authentik server for authentication and authorization
          - Grafana:
              href: https://grafana.services.mkz.me/
              description: Grafana server for monitoring and alerting
          - Karma:
              href: https://karma.services.mkz.me/
              description: Karma server for monitoring and alerting
          - Prometheus:
              href: https://prometheus.services.mkz.me/
              description: Prometheus server for monitoring and alerting
          - Alertmanager:
              href: https://alertmanager.services.mkz.me/
              description: Alertmanager server for monitoring and alerting
          - Traefik:
              href: https://traefik.services.mkz.me/dashboard/
              description: Traefik dashboard for managing ingress
          - Longhorn:
              href: https://longhorn.services.mkz.me/
              description: Longhorn server for managing persistent storage
          - Vault:
              href: https://vault.services.mkz.me/
              description: Vault server for managing secrets

        - Web Services:
          - Gitea:
              href: https://git.mkz.me/
              description: Source code repository
          - Harbor:
              href: https://harbor.mkz.me/
              description: OCI/Container images repository
          - Drone CI:
              href: https://ci.mkz.me/
              description: Drone CI/CD
          - Minio:
              href: https://minio-storage-console.services.mkz.me/
              description: Minio console for 'storage' instance
          - Temporal:
              href: https://temporal.services.mkz.me/

        - Web Apps:
          - Calibre-Web:
              href: https://books.services.mkz.me/
              description: Library powered by Calibre-Web
          - Freshrss:
              href: https://freshrss.services.mkz.me/
              description: RSS reader
          - Wallabag:
              href: https://wallabag.services.mkz.me/
              description: Saved web pages to read
          - Bookstack:
              href: https://bookstack.services.mkz.me/
              description: Bookstack instance
          - Linkding:
              href: https://links.services.mkz.me/
              description: Bookmarks
          - WikiJS:
              href: https://wiki.services.mkz.me/
              description: Personal Wiki Instance
          - IT-Tools:
              href: https://it-tools.services.mkz.me/
              description: IT-Tools server for managing IT infrastructure
          - Send:
              href: https://send.services.mkz.me/
              description: Send server for sending files
          - Yopass:
              href: https://yopass.services.mkz.me/
              description: Yopass server for storing and sharing secrets
          - Excalidraw:
              href: https://excalidraw.services.mkz.me/
              description: Excalidraw server for collaborative whiteboard
          - Redmine:
              href: https://redmine.services.mkz.me/
              description: Redmine server for project management
          - Privatebin:
              href: https://privatebin.services.mkz.me/
              description: Privatebin server for storing and sharing text
          - Vaultwarden:
              href: https://vaultwarden.services.mkz.me/
              description: Vaultwarden server for managing secrets
          - Snippetbox:
              href: https://snippetbox.services.mkz.me/
              description: Snippetbox server for storing and sharing code snippets
          - Paperless-NGX:
              href: https://paperless.services.mkz.me/
              description: Paperless server for managing documents
          - Emojivoto:
              href: https://emojivoto.services.mkz.me/
              description: Emojivoto server for voting
          - Microbin:
              href: https://bin.iop.cx/
              description: Microbin server for storing and sharing text
          - Cyberchef:
              href: https://cyberchef.services.mkz.me/
              description: The Cyber Swiss Army Knife - a web app for encryption, encoding, compression and data analysis.
          - Vikunja:
              href: https://vikunja.services.mkz.me/
              description: Vikunja server for task management

      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - longhorn:
            expanded: true
            total: true
            labels: true
            nodes: true
        - search:
            provider: google
            target: _blank
        - datetime:
            text_size: xl
            format:
              dateStyle: short
              timeStyle: short
              hour12: false
        - openmeteo:
            label: Paris
            latitude: 48.8575
            longitude: 2.3514
            timezone: Europe/Paris
            units: metric
            cache: 5
            format:
              maximumFractionDigits: 1
      kubernetes:
        mode: cluster

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "false"
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/description: "Dynamically Detected Homepage"
          gethomepage.dev/group: "Dynamic"
          gethomepage.dev/icon: "homepage.png"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/redirect-entry-point: "https"
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
          traefik.ingress.kubernetes.io/router.middlewares: "authentik-ak-outpost-outpost-for-homepage@kubernetescrd"
        ingressClassName: traefik
        hosts:
          - host: home.iop.cx
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - home.iop.cx
            secretName: homepage-cert-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: e3129ce2641e203f3971f58089fd955d1bf35640d4e40c401a42c3452d1272ff
  name: homepage
  namespace: homepage
spec:
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
      version: 2.1.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: homepage-helm-val-homepage-c8244fb9
      valuesKey: values.yaml
