apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: jaeger
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-helm-val-jaeger-c8aded36
  namespace: jaeger
data:
  values.yaml: |
    # https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml

    allInOne:
      enabled: true
      ingress:
        enabled: true
        hosts:
        - jaeger.services.mkz.me
        tls:
        - secretName: tls-jaeger-cert
          hosts:
          - jaeger.services.mkz.me
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
    agent:
      enabled: false
    collector:
      enabled: false
    ingester:
      enabled: false
    query:
      enabled: false

    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false

    storage:
      type: elasticsearch
      elasticsearch:
        host: opensearch-cluster-master.opensearch
        port: 9200
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 61580570ce52273fd7e768bffbbee5622f6879e9fdd7417916eab80cf7464133
  name: jaeger
  namespace: jaeger
spec:
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      version: 0.69.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-helm-val-jaeger-c8aded36
      valuesKey: values.yaml
