apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: ConfigMap
data:
  kube-prometheus-stack.yaml: |
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/redirect-entry-point: "https"
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
        hosts: ["grafana.services.mkz.me"]
        tls:
        - secretName: tls-grafana-cert
          hosts:
          - grafana.services.mkz.me
      admin:
        existingSecret: grafana-secret
        userKey: admin-user
        passwordKey: admin-password
metadata:
  name: kube-prometheus-stack-cm-c8292180
  namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    passwordKey: AgC7dhPNyPCSH/TWRSe66PN+yQI03dHersP3HOVsoJMCr+WPLrhU2L92wZ07Q5ibWSTTdx//lxFptA6L+kkLHOIWXD3gmGx63sFQcz88zC4NXfaxyc6XA2CdFyinMl/qjmdS76QLa7/Yfw1tTfseMhcC5Mcy/dpxH5iZlembJK6vh3YQZ8j2ppfwnfRsMvU9V0q2UN1bxEl/JNzEpaxsD9+fGEfQciCY/5Kg201C5JkiFOBVdvC8486cmhLSgrG4BT5Lfhekdg7f4DGySE+aZMVyxFML3qhWPFw2xvrwB8cATNaNaBgliDp6NsU3wynYj44yZd/Zbe0jD/pilg/AhoFndnmLad/X3tS3TVnkGAOzgDtQwkBM4hSLvjPzY/yYHVl/uDaw/B1WedqQz3Qqb0XX17Q90T71Sthyq68S74w+0rXHb3g1P1s2d9tK21CjJrIYxBnxtwZrfQzOHgIO5gKq//HGN2edKwOCcZcAzH08eEy5l9F1lD0haujT02AEyUIBHhsOaLhEzg058SlZ5aZASpVZbr8HLn/BBsKhpTpv8FAYNA5CJCL+IbbtHfWywNidreu/ifxWn/Q4Ir+lyuZ022yhMWNTULBWONK5OptuO2ETnTWW2CwbS5lCSGEaOSMj9uaONmfGxbzR7ayxldygvvhC7YwrOnHbyOQU6/xCiaFf6d5a5BgvOhaUt96I9WZLPWRw0SN/IvhdcuKdqB8cWHSHfpgj1CO1
    userKey: AgBOl1LNXPIEtspMvfFIxuAy4YYUWG+HyEfyJ/169BtVY7Jcgt1hQsib0tH8VYJE/qEc1hOUr+Q892pf6BBlRS4IbbczSRNP//YmTss3QK6xg53AJENsHvtVKpmnfOZIAf030M7HPbCLUwmv5SWH1OMnCPG4JVqVEMn9/2q4mBQbafQ9yzgveNxIzJWz5dexzmuG6tKHa7P6aYmRbeLiI2517ARxXlSJhunoETW20k/sYUueSQ1Ai6WHKP7JbPJ8W7rKWI57cck8IM41/X3RzPuf7sVKVCYBeA5q63vh2psWYP7ffLx9w4Yucv8xCksp4d/XD+Pr7GRIL1X0cchr7GfQx58WSeoTL5sQLPZCXMKyzfl+51n197YiB48ElgiWrDyxmJ3H60g7MDePT85AYvmulUXjhUD80bIN/c5xENypNRm61JWTmfDO0XkyEBBbFN6gd3KVZ1KDgS9kCQEB5px/+/d3kHajRQmulF5bNS6O4SSy3gY0YjK9US3cYVp3YiCcmROMN/PQQZnFogXZjstgZVqNba6yJSoNQPMEOoIQLLPExJ2NNtXz2HADNgQthvxQ14hdE51CXFU4Sb8EhFDSlKrns1JWei+mc09mPDEztmTsO4Xmj6CSxm3MVhFzHUqsxWD1MUcK1vGncMtoa+6nNZH27BrWEYBXEBErZ3qL6kWBM0xZQoPKGqpMO+ynf/FQJRjvKg==
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 1795fb8e4df59f0074bda1842f4ab97b0f61671c9c8c4e37a393c248d6e6ac6e
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 41.3.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-cm-c8292180
      valuesKey: kube-prometheus-stack.yaml
