apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: monitoring
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-es-grafana-secret-c8d6fa88
  namespace: monitoring
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/monitoring/grafana-secret
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: grafana-secret
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-es-grafana-oidc-client-c8cd01d8
  namespace: monitoring
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/monitoring/grafana-oidc-client
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: grafana-oidc-client
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 32Gi

    alertmanager:
      alertmanagerSpec:
        replicas: 2
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 512Mi

    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/redirect-entry-point: "https"
          traefik.ingress.kubernetes.io/redirect-permanent: "true"

        hosts: ["grafana.services.mkz.me"]
        tls:
        - secretName: tls-grafana-cert
          hosts:
          - grafana.services.mkz.me

      admin:
        existingSecret: grafana-secret
        userKey: user
        passwordKey: password

      env:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_NAME: grafana
        GF_DATABASE_HOST: postgres-monitoring
        GF_DATABASE_SSL_MODE: require
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://dex.services.mkz.me/auth"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://dex.services.mkz.me/token"
        GF_AUTH_GENERIC_OAUTH_API_URL: "https://dex.services.mkz.me/userinfo"

      envValueFrom:
        GF_DATABASE_USER:
          secretKeyRef:
            name: grafana.postgres-monitoring.credentials.postgresql.acid.zalan.do
            key: username
        GF_DATABASE_PASSWORD:
          secretKeyRef:
            name: grafana.postgres-monitoring.credentials.postgresql.acid.zalan.do
            key: password
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
          secretKeyRef:
            name: grafana-oidc-client
            key: client_id
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oidc-client
            key: client_secret
metadata:
  name: kube-prometheus-stack-helm-values-c8217b7d
  namespace: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 860543c4f8676cf058b59f43a8fb82db171012cc1ba5c3de0e23d83caba94700
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 41.3.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-helm-values-c8217b7d
      valuesKey: values.yaml
---
apiVersion: acid.zalan.do/v1
kind: postgresql
spec:
  databases:
    grafana: grafana
  numberOfInstances: 1
  postgresql:
    version: "15"
  teamId: monitoring
  users:
    grafana: []
    grafana-admin:
      - superuser
      - createdb
  volume:
    size: 512Mi
    storageClass: longhorn
metadata:
  name: postgres-monitoring
  namespace: monitoring
