apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: ConfigMap
data:
  kube-prometheus-stack.yaml: |
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/redirect-entry-point: "https"
          traefik.ingress.kubernetes.io/redirect-permanent: "true"

        hosts: ["grafana.services.mkz.me"]
        tls:
        - secretName: tls-grafana-cert
          hosts:
          - grafana.services.mkz.me
      admin:
        existingSecret: grafana-secret
        userKey: user
        passwordKey: password
metadata:
  name: kube-prometheus-stack-cm-c8292180
  namespace: monitoring
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgCCADVAPJC4DoSw0A/tI1sjYMRm0KC68tx2exEA+NgNj63vlWjj1mgbZjBMDRil7z/knMQqwuMv39G10I/RpJa7Sady/YmnCWkaWQmfdW6cMeemFxGqy1ARGlbT5l1G4cYQW8bViBC32g9CAJhXVzYxsIcO1qZgkr43aJeXzWvT2VhN7whDD6T4gCg1/JolW7jHu7blGdUP/qLeSirFn/TevxTFbpU/ebvy9ixUuqaIbDD1dg40k/1C8HNnFA3I7AV6VuOVE8GbdxWmS8Rr86okBw4F0u2FQebmIx2wxoDfyeJIY7qZix6a8yYqC6t5c+1JAQ41UKdNlYqlGCBZ4OPqNaJHLO9JcLhTPbv4SpeFS0vtWriF5wMQXEqlRH6Bo7vP0rdKpic08PVkSRk2yK5013XTDNI2lZU1/Ck4UKmTnIV7e7bjgiWsMfgv1EbRmLeEHMhuOhEjS5z0gUVjWacxXBhZEgz/nHypjplVP2fOlXNAt/QMOrz17d7Y19PrITRutp2gs0tpIkepXV9Oz96frpz+VSfDxbbsumX+BrTKqXpDiHj46UagOIn1H0BTgpuFO/cnOnzIcyRjoVoNm0Anc+J3n4VCuN6dMYjmRQfip3aNNf+8o1Be9K2lzxrWsyJ7t0LKO6UTFIzsTmCTNRiOg17WsrSUA5K1dVho02cRnIcZI+IYmC26Uy72xXMU4OLGJjPVzFaWUOiQptvxEBWZ
    user: AgBYdmNCWw4ai42G50Fl1ydHNzKMTWfcpJGKqNvTaNUxe79EWQY0/fvUi5nWWzLNTOJpNHVgISPIdcW+WZT4Cu7ZPvmMzynEcqDMjaFWkOlbXtCrOQTfIOKEX1vAeGB6NWlLflpzqGykgiaUUXZ7xI7qvHv7ooUfLi/e7LTgZxDfqBC6DFrJ3R0YprS+PUoqHZTfkr15I4dnz2foA1A50XpLMweSqrmqcR1eHUSduqubplr5xIfUtdOhnuhCCe3H6PyjEoicCZ8cBPqbhHCAg2TwDifZrn9efJXkqT0WheZn17p2jPuUeCA+RrtOe8NNXAFm0+1zeowzVJCVCCone0b23SJ1Syre1muiTWEitD1Cs78xAn/2iAUWDUqgolrgV6LgeU8zwwt2013tbzd1ykzJv09tEjwzG2l49bv9+3L2lX18IwQgUGZToJhB9MQt/3z9h0sO6D2WelqLNpCA7GEywSCMIZLhszR9pTUIVPUZRxCQzgun51iySeGWiC1XLfF8WSPcG3YrmLWq5SWZI+xA4vRRHLtOyTSOubYAjF6gx2R/Rd4pMgIU4V/YnqrnlWDpnZz6oNQ6dHDM+vsRSRMQdJ7IJ4hdxvKMPzflvy1GptbqCijG1f/3bV13OWGhyWX/biHCIhcH4rxIQLbfuqs+BeFuWFdOUoSvB2d4HRM4wlEPoQNuCMhbtesfKFxN/uDpcGvhZQ==
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 0f06e30052673dfa173bc47af736d1be3005399c0753729b3e1c832267706579
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 41.3.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-cm-c8292180
      valuesKey: kube-prometheus-stack.yaml
