apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: loki
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-es-minio-c8c26923
  namespace: loki
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/loki/minio
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: minio
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-helm-val-loki-c8d03bab
  namespace: loki
data:
  values.yaml: |
    # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
        - from: 2024-01-01
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
      storage:
        type: filesystem
        bucketName:
          chunks: loki_chunks
          ruler: loki_ruler
          admin: loki_admin

    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      persistence:
        enableStatefulSetAutoDeletePVC: false
        size: 10Gi
        storageClass: local-path

    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0

    monitoring:
      dashboards:
        enabled: true
      serviceMonitor:
        enabled: true
        metricsInstance:
          enabled: false

    # gateway:
    #   service:
    #     labels:
    #       prometheus.io/service-monitor: "false"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 884f5430ce7b5bacd867dffac6d933327f05034b8512a5bf93f9fa3c9d4a5257
  name: loki
  namespace: loki
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.45.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: loki-helm-val-loki-c8d03bab
      valuesKey: values.yaml
