apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
spec:
  encryptedData:
    CRYPTO_KEY_CIPHER: AgBs1HRoXzlFCPX3WApqH1QxaJTJKzfrrJx82JxkEm0zT2LkOErfezIBIybstRYhIT0G5uYRVtwSCs9pxpOJIwofGs275Minpzcs8qsJCkZVU+1FQFemTGh4aevAOwHaV1SaimQy0tAWZsrRZ3TAbJfTGGbKanjsQ3ZprPfLBUoLgIjfXUdGY2mjwcVWjsCLWHj2Q/T2qGEGlB7yaK8NAmOY4G6tAvxT9rHKYG22Td1vKH0LzLUOjWkvF0KoxaEV1jdYjCtmV3GtiksjqyUgr4mP21svq3T5CeJo/LhtzEqm3jiZtpJP1dQmNrh4MCS2rq4+mH9KxWxIFz+zIxEXhZDxzBcx3gWNeKuzdhyBGJ6cNbL+2dcdm6BvKlCZva9wgyd57I58sS2ERWbOUS9L+VFIrdxJDAmu0x8Iy2v2zDGnIftj48U4zl+R2N5GUcpEFAJu8BWKC8AVYAI3z48Jq8o2gHNFlrTmKxX+R3V4Sl5o4k5NRwOubuRF9ulEdpSl+aeFUMt8YPY6Sydq7mSvziaiCSmHxPXAoN0J2+7Wcp85Y7J1fm9gZGcb/fNkEMBE4A2Z3xcJbJ+UaldSy+u1WfVTLn7VgKZdQJgmGa2taxaYyS4HNZhGPIoggV2X/QlOwLRUw3isOwj5a6cLWFx3P4cmV8b4puX+kvD4Qyn9QJWulnHwfwfkfLYm5kTHAPIBPcZT35w9fRsxSC/V9RgQpfc=
    CRYPTO_KEY_HASH: AgBdywpwYo5RkYUF9zF65wiyxkCFuIJ83vuwt+9HctjvzJVdMEULJOPZl/VhxKyCbGBwnlySSoYEGwdQwM2fDYbuT/HSQiwy508qE6wI4wtMydgNzO3RRLieceCaVjXRG0B056Nu8T+FsenAOnFjlNnCQqh1UvoPPPzG8YaWLpk+NzbJrMyTPm2LYY3fg91//LUaZnzaS5qihRS8RLUCiEKbie0PArAI99FvzvV2WDb2q/f9tt9qoV6NpiLZt1KOpYXz63KmroewjauqLI5lgkjootyFi2sYRNwWyXSrR1q2iNdwVrVVqbeI4/gX6ATA7+xn1RpRoLVC0pcgLU8CahLEPkzOiOZUZvMxcGZK4TS6wUW4L9HiOHJ2eWZKp1LuU0OgdcnN515sdfcvE+PjI+TYQRo6YEhX8tV4l8nA8RhQWkLHqR9jLTNKif+ky7lVekx9kmv9m9Boj9WLcua2qE7E44On9IMP2YczJ+J5tZCbo89uLA/Xl0JGKeyMVC2rmczkB0j7wx5RHvY+JN4HGEI3KlnBnBO0mwjV97XVAVIMW/9TB8yNx0mWtlDiMbRzDASCI5Truo/JeEr6BDJkfN4Sxp6AntsQr4/jJYntLyK8JPULSGWsO6qeLatwO+Xr3/0t328DqzA2xSexeVjeE5letUcofRYOrtk3ffiZVCUBD98XVstsETYqyz5ww9h38tV4EX+Xd3A=
    CRYPTO_KEY_PROVIDER: AgCkfLOzp9Si++tup/FIVMq6dxLiiNPuXF4xgatBOzw43vDG/yQAvF/EOxWRQe1zYXXi1R7sNmL6elzSeQZQ4jbKNlveajFVK2wqISmevX1uNytrhC9udOh+bKC8mAxZrGitiSpSI2whRvFp52plf2+vNwyoCH8Klm1kA4MAn0Vkx4rp5h+F/yiIAXwcTS0feXjmi4F3Eop/j6kqz/oFXkxyjcD00+7DImqZkBzgKSHH1DdY6f1D0Jl/KZ2H/5ZlFt1oWBV0Sst2Scqz3Di1Egzsu7FHYSDS1v1xhsDnXuPwmYI4AePSjCIt3JIUHMrFTN5qJwrta0hQsAK4qRtxbEimF/ARrvPXOW9NxH1yFWR2EXJFEd8cLexNqnmsg0k16O1wcgVcysmmRnlJZ8cylwuZE1t0e2T3i/tLZ7iHVk869OgNzajtpE4D50q5z6WnZ9e/L1kyBE/iSZl6QixIiZC6WgqCE5I8m7g0JZR0GisAX6rp437ReTC/ZUmXRVm4+v6DiCi1VxQ58oOtsKbn1T+WZ9phGeBZL194cVuTOdeECErMZpHPZOHrC27+fGXuOXdVgRAJuVPlXpvpyj7Hu1QW0ltZ7SR94g4NWuw1UyRWOukU49zMcEGLKAJUNwkmn7xGl/u0oGqZJZ6NPtpaRPMR7iTrFewuyeXbrW2m/PzC0KKXHEKbnRqyYMQBC0lmG8uQvRflKOo=
    CRYPTO_KEY_SIZE: AgCyVBbO5Bn9NpEGoqAKZIDZtmEw8DYbN+u87U8iU03z6me9XShrje4ks5UfA33TdL7bUdyIzrxsGQnESnCaNFw/aFv78UqppSA8bf5QD6ozxu8oxqU7cARiSfLLeKeq+eGSJi9bwtKVMq1v69YFO+qEeUNPGWsPewCJvHgr4BmLU2a4TZIrGDbWPhv4XW2AinNHvkNJUIeMUuh94r0nnU1RKw2G/38AocSrKhW2V+4e6rX9J8dryBc1kKYw0F/x9RwoX32wNjN/2GDfhPUNn3KmB7j+ES4g/QHPMLvFxJ4Y8RrcuunO1/mUFFdSVtD3LuOUoU/DCXL8hvOLnAqF60THhvJCzqrxLUMOyx1Mi7/reXST7YbBawYW0j/W+cK3vuhxvN4HIRCAqe3Ix1J5zWadUNKCzXo/zrioG+qNDg9oTjhhyNXMNjbMOvZ5ZPiD7Mbkuy+40tqF6L+r8CpatHCdfl2nBSeggYQXvUcYFbkL9tAivBvB2Lfym207RU0NdaUwRPSXSNdZsg+Cw4jy4VYRwtcREVrbmRBkwmYYiPZhWk5xXKF7NbH3zZE0kpJqOO2c6087DfNgPdT1Xi1fyO0Q6n/mhhncLPIYj1kJ2q1ZEyATTzHo5bfznzALP5TSJJFrW1PFbLxhfNrFegysGaYYlvjllU1Aon6yqBd7iSP9gUvjRccavebURWwXpXppmsBVhBg=
    CRYPTO_KEY_VALUE: AgAHza4E9Pm2o9+NHjaolZrJ/E32LU6a6KcyBg+am6bME48Wc/gjSlZNCwQALNtTb5NdD51Nr14d01p0WKZ2962fzB434eL0bH1pimqQQ6zYuT36K9Eb6HSsF8fzP7yHMWqfWZmxBXsNc++L33HL60SYn1nZsybtDPr4AO2e0VKKd7jQFFPFaKZET677VjEUbGVS6R3Q0R4YCXCwc9q6HILGohsdYJmqYcn7bMcqUc9aTfchK6eNYgFKFFEI4ra51KU9gzgKHHKncIfROPeDq6TKmoiFgX1RZm70nTObYT2pG5Tna2IafgkBDkHOPgMmcypgW4RY0I3hN4O5i09CZrSyUYt1t9arxO8M9HGq1xTF3MxN448pfwkMnD5Qq0Quib1Il+jbOoUg5xKEJh84sSkDCqGvnCmlRufhLmf8oUCuRYLVkyJgqfQjFSvTVDyj3a6uMKuP3s4zxQTdYQRKrjrfLf6FrVu+6zlhL7Il+O74uSKBevmDVtM5BhLYiYhqq7DcuswiT3x4GUe5G/twT7YTCvmIswxT+vbIe3Z8Dd1G4qnGD91lpguAAM8fEFuCwrHfVw4M4Zn1IjbDYjB4xdyE4017LuaxTnxyyGvLYZ0Cc+NfQSHRDXYW6pzwKj6yfTgaCEBfitmK7KvJMSUrzaqacJngXIuwY23MdMUftFZKIKSN/TpgcjYGFR/IM+bp/6JzmteTd5EypSL8SiOJpLFIfL4nK7ETRZzeZA==
    CRYPTO_PBKDF_VALUE: AgDTO42cqVxOGa7vO2A9ZyeFL/8818b6vpdUJFdr26lycb9ocQp0LbK/ubLnSZiontRKFD95QYf5Hy+iPqHVVw9io6VgbI3I20A5cRofFNIZQD0I4ht4bLTqxlyYTGCmkY2GST/o2JJ1LopcYKZBDmuOZkCH7JaPk4AX9N5JDu7Dhm0oOpFh8zaRvO8fkRrHu4jx4e9b/NPGf7czFZ55cT+S3tNtvCNeyspS0uX6CVuKXqXjf8c7VAJXWNgPXm6Ye0Yjp7+OtiXIun5OD0uVV7XDUufdjhXkd0z9iXhScBZZEyYruKFTqIcCvm+ZOCkAUmkmQioUtV5rh+tBSv6ZA5jT3A0hIrbna6nSeyTE5orayfN/yQ/I8QgkrAkPIewhGxkbqLX2YFIOnrd4IFztb8r4OGdCMjP6oU8Qv1O6s1bC2N/SbpBsL0DrpZGgboUfTwC9s21Qy3aH8nB70B1Pu1hBhWouxmGyEQ8Rt6z4XR6SmNbCwMV6rQGp/hLONISeeDsDtaiT1tiQtB8YVM+e+qngLPMI7RrnACetPzuv0Oekii6qVSlzk9F7372lpaak417pNjnled4dHK54De+O1/+Y3rGKTrwuinEDAzn1wMLJ3wCD3W3W9E2CG+M//vNd5YbgeKcEq8AJiM4abao9dx9mnBAT1R8sqF4lPqCr88OMDlG3w09HO6mrNWgZgknwp/600nOmrcDi
  template:
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: longhorn-crypto-global
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn-crypto
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  encrypted: "true"
  fromBackup: ""
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: longhorn-system
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    defaultSettings:
        defaultDataPath: /data/k3s-longhorn-storage/
metadata:
  name: longhorn-system-helm-values-c84bb4f1
  namespace: longhorn-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 59a51bfb16cc81a5c5ef85670ae4c2dbee3a833db02ae2507a7db6fc5f5d6099
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.4.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-system-helm-values-c84bb4f1
      valuesKey: values.yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-system-es-basic-auth-users-c8e97f64
  namespace: longhorn-system
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/longhorn-system/basic-auth-users
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: basic-auth-users
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secret-tls-www
  namespace: longhorn-system
spec:
  dnsNames:
    - longhorn.services.mkz.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: secret-tls-www
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    realm: Longhorn Authentication
    secret: basic-auth-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-system-ingress-route-c8c92fb6
  namespace: longhorn-system
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.services.mkz.me`)
      middlewares:
        - name: basic-auth
          namespace: longhorn-system
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80
  tls:
    secretName: secret-tls-www
