apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
spec:
  encryptedData:
    CRYPTO_KEY_CIPHER: AgAl+8NJCZvicrukusoTkrg+CYetiJb6485U0zX0v5cQcsnQq7F46T0GQpx6wnMMM4jUZqaYnm4GfBMtfH19Z8Pm3MXYbv/aIE3mzCKgvJcY0rd5aS7VgvLRuK7fBRI0z2iPEcVibWcF48AXrt7I18sYtZOrNVHIKmw22iIe2ILPdSIxP8yYDYdE5TVTPWiDGDO2xo041V83XkEoV82HWQmtUt4fx5iEyM+OrWi0v8tRqYO4yQxR3gpfVSLuGNajUri+2w/r+xpcaXso0pAmh4HX8AVGl8I7PSHhRw5R2gVo9DJHf0NFIpMu2YA6a0xsLTYpTFhBpQ7rWn2UJ4ZPAhsIzbad91R6WmRhv7AZwpYJmg+RUZc0YK+0HexhbTLdN2AH7bgee5OE31EPeYY5Z7e4uWw8OyrLaVv6+hQZl1jgykpSaDj6LsdacfEvyf8Opps7PSV+I966hfyDU+VkZkJbdyk4AYRW/cggMFt+fiyWvC2Vzbx2BavA2GYudmEcVqUVXz9bPwVddYqRL8wjRjaa+dxdrAOA4Vre1ILi0X3ylQFZ5bLB7u387+NhXTzg3AyM8WGopExF23GYMoKIZlzHHzHUPXnxHS2MpH7lBkuSN2QoCD7c5L4XzUly8pYP5rAYnH5BWLYti7YHa0S2XnX7EGpfrhxNb4uyriSb//mI4DLtgJUkQDYuW7X9YxpwbuTFPg5dgo5lmA5yD52a9O8=
    CRYPTO_KEY_HASH: AgCBnoQlm+emepq/LFzE18/7QNKtEH3mHTAGPbu9XEV4b/Pwy6pqunJfnTcq5zoKL5CV3PV4B1ZN0xuAxlf6Mc7xCLCCuvKIIh3YgKCy1aZNd4VymO2VVo1MBGdzbGfFKqjsCkhut4MYPVaoqk5r0wSLsZ8FAVz8mYiKyPANMJ+9HwLwk5laPMSrLfFlKRuEFsTanoSwZEQkLM50CME4b7+KpAFCa0Kn8AbMz7ue6ACXCvM7yRMWCLsAmPolrCT2EYXQKIasbI0m2+AIlCn27zwRFa5WIyGQ9ycdMm9WTpjvlGdEFxTU+8yp0EotGi8Q6H4k1IxGRnt7PG2y2wgn3Tp3boJ1f4WKN/Cdk2FxIisSaI8YBT2ARkQv63va4eXDUMivW58t3rPCARRxRH9tRZ26DTtIKZ5oIhGCIaU7m+XRo6scQNe9MSmYvaSmYueYO3p4sTcWOrUczAzEF2mqzTFhzTry7t/wpOcsHkoI4/Bwy0ZR2xmjpzN0DJmF0sb8IgvtAB3yQ+v1DhvZFfWi3oig4hyg3fn9UCCNWS1zYoAeuqTTwB32KqQYh8uzaThGZYt572KwFWtyWlqdKzOyeMA1I5Gs4rDNSvuYedQ9ff6fQwzgyCani1DNczErvFSXIf0GsARx5SP+rkDADxp6nIGoYCeE5m56QjRFTCoSRPCJZfPJUgT+IRyZQIvYWeKNYxxtZJn2mW8=
    CRYPTO_KEY_PROVIDER: AgBriB/wtVOoyUzFyf84OYCNmKpBWE2JKxM/t5RoGknTqgXcboxSg/WH+uKwUQjl1oXTG85JdlMX5FXYEw5XY+UqCazc4efiXQTVvs1vSqYnm5r+cRVw2hJsX3pmZqp8zKbHmk5AWRL0kuuNi1E6x5zJ8mzleSA2ZfYGIRChstQ2c9vPES+D9IbDgyqOMtxGqGje7Ty7xj+zmKK3aREbJK66JWTpEYECvCPYS7/dZ9IzdXTNom2bJlybq9gpY0W2/Hz1OlgUU+VnkxKEQP1EsGFdkYyj8kOrdZTWX0doUbvkcoHH0lUhjBON5tIrdbXoQg5J8yaZ0bi18N6D+oEWCWYsVUg1hXwz/BZCNX8cLZBMg78HPEmdJ52Mn82fO7iiHCgm7LKoBPtQayJ/gehMVOwUS0DKgOIn5Ue8LRW5VwnKsKn3bTS0RtPHPny39039ycZ1jZteN97/b/OUwexFBT3fG5EhmS22iSBuf7kdWzWZuayjrWu93Blo/G+2M2O/Dzh5cJRaeWOwx0rC3o2WQUq8b9kdtxbebCtI1YTEqkg+jItvfgyedtNU+1Nu6S22C0Y6aAI2iERfPtVJXX04zM78HVEHlS5XETxOblPXwvOQplADSLUy3qeCXIVCYm3WZ0n+JrHPzey9tMPDPSf4NLZJi2yjt9u0UCCsjNGn/AgHtaCP+s63i1SakqcVbq6Lhy15Uf7mBsA=
    CRYPTO_KEY_SIZE: AgAXmCIDpOmyPoVzKd4MMMsSZyqzxzId1gSOhEoMYV3E5DH1DP2HFv6s4MfrONQOFASjABliQbMa3P3VqH8FPqXCzyh+N6z5GNFRM9eeQHQ6TcffxFHRlA2nZ0QqoHsSvt0S0VbXIqj9lBsvIgJKEteQ8dRBWsF92BPHySk9GtlVMEAyGt2bNOyR/KO7wWQX1ses/rK5UfTrRd5OWfLj2KXfaD1dc5LmIK5xS0aBEPP8Oy7/G0SL7rVVe+1yViQqqN+I1WzXIsKG0pLEOOG3wxrHJBHe2JzJVpXp1plIWDEFJ1tEKQ4XExrF4iQ+mh88CbzIX6apARdpfvtqKgVtDMqnOKsZMWCQv4UP3/iYLwTTOCP02bFvQZXnfddhSv6k9kciV55wf0kTMKJcHq8Xzl3vX3tGQdHGUxmmBSoJJ+ztmuMc/uThHFZi9kovzA08V3gJ5EImDGju2snbRO2YDL+cWAGJ0jcJSdoTN4S4pjpbDEDrNqcEfkvSCT1SQl1Wv21NidSDw8PRDiGvwA+W2Hclwsmryj4Yv6M18VKkWCXWG5BfsflITI3/+tQt/t7C9W17fQewSL9O7IE9enppgaTLdr1vaASHe29E5ATljmFHGwse+jMxSlo/Ueo0ewRXn2ckBCoKtrdJs7f0ABLRQXjfvknU8ue+tUU+2KeoyTuxOIkefhXLNxG321CaW16/waVFvfY=
    CRYPTO_KEY_VALUE: AgC/qLeFS+oHqaDiiCJm3JyNvA5dk4MHOFxvGfo7YGpjB8YniVx54YzCP8EX47SAdX1D03DwYZVilSHe7W68US8bFSHRCUQE5PKC8ZcvkwJmwV53dwecdmLpwevUBY4KZ8mwT9CAs6g+10eQ2fOF9ydZB1QnOrwV2Tkp/tPoucswHSV0FbZmBWnEq96VZjD1GEVinPVXiGnmbAsoVWBBPqFNRb3TqvaGb6OE3W4SUzrZ4Vo/+rNag6NDd8xQx2gshl1M5xKwar33zFjmAKkKWPA8pDsKtenBSoxxGz/eENlZMvPJLksi2uaBc/U/3ModTGfdM4uuMTM46mLUvP1aiMh9CbwOXvzihnUKQ3E4cF1i8ZQTYkoTYND78l2iWjkurGCuayACTrE0CGJN3YqyyZIj3a8Qaa3KyghNkKbP5RAE8McnzcRBxbQi3OUXIQMqnOqmrT4uzpmsMahtce6ib4pYURunayOEajh+YmTzYWv2rrq3poEk/r+wP6n3SVZR6pj2PoQwHN1HMYIrQqDwwIpgvoBmj3OQ1mtlpdiIrIj2NYa9K0jRKa0L6WWb/RYdNI+z4p/YUJ3btn4ZA2+AjO90ecXGfkB+MKwO4QBdiljc25nugIfRuhmQ690EPojJ1DFL4HU+HSpjXLAtNpxvZE6Up5pUjniC9iDUHq1xMwCynA3RGg9DJik8MyHbDwtkW17jI328WTQm5QHvqb/ZhXJA2ukqjtjjCL5k4Y2DxYW9XDvPlteb3wKXz+rTAfzAaLnBWaqrBJ2BSZ8kcJdKEJAO
    CRYPTO_PBKDF_VALUE: AgDKQtI+u+mVmrhK6vZi8PLd/g0hwu6n6132NRDN0pjf1TIjonIxvY7w/VDcYGdkz/a7FGQrs9sc8gNN59gJrEAuXNiYU1fxICdcrrvZIqrNvJKgOnWNbBxTe7vV2E7goYc238YHdJudIYHeas+9KB5AGHj5YyRfrjE8jMMG03PNykhIaG8ZE/x9lxs694gQNHSCmaquvRkDjtVbRQ5J08nAiUobLkNHprR+Qzz5lifPw6SpY3pUvljFxYmmpOL18t9F981bBC9T7B1Xt4+YL4oBCq8u7gWeWuPzEr1sCgrte9lBNmprEf+Wady+nV3wC+YQtAi3gjcWC1ygTlnrBU3rtosf6frouQbJ7Y7cIdKDpv1iQIFS2YTPJaUixCsNhxmhi6IrMrczwDOBunGA9ZIuj9oL2g0ObhRePixqNGtOvDvQeZ/BvoH35GjQNnSVhUiyKqdlQ0JgD7iFonTIa3IS9sTd26WS+ah31Aq66hXIC05QbPMpaOMEjx9nktMblKDF1hNC97d46vEShai5Qlbg1BAORZ2Otzb4wpFsKmP+ZlPtWiKSn1ypTnQmIgvnrM9/SkrhJkxt+SD6UpSe+19CbgzonC+CaU2fylOzk3Qr3bvY6Gc6ALaYvxI5QhlaNuVsrWW6IbTGIMH2ckkb3vBZ9kM03b1/UD/uMcHIw8K5G/KyLbDLX580Au8kmk7/IVyDUdPWpeKy
  template:
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: longhorn-crypto-global
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/node-publish-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-publish-secret-namespace: longhorn-system
  csi.storage.k8s.io/node-stage-secret-name: longhorn-crypto
  csi.storage.k8s.io/node-stage-secret-namespace: longhorn-system
  csi.storage.k8s.io/provisioner-secret-name: longhorn-crypto
  csi.storage.k8s.io/provisioner-secret-namespace: longhorn-system
  encrypted: "true"
  fromBackup: ""
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: longhorn-system
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-system-helm-val-longhorn-c89d0ba2
  namespace: longhorn-system
data:
  values.yaml: |
    # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
    defaultSettings:
      defaultDataPath: /data/k3s-longhorn-storage/
      backupTarget: s3://k8s-backup@us-east-1/
      backupTargetCredentialSecret: nas0-minio

    persistence:
      defaultClass: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 4f1f3b9c7e56416042b6f7ffc8ec4ecc41525570f81ce55be97f419ca81a8051
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.9.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-system-helm-val-longhorn-c89d0ba2
      valuesKey: values.yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-system-es-nas0-minio-c8ce1a0c
  namespace: longhorn-system
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/longhorn-system/nas0-minio
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: nas0-minio
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-system-es-basic-auth-users-c8e97f64
  namespace: longhorn-system
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/longhorn-system/basic-auth-users
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: basic-auth-users
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secret-tls-www
  namespace: longhorn-system
spec:
  dnsNames:
    - longhorn.services.mkz.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: secret-tls-www
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    realm: Longhorn Authentication
    secret: basic-auth-users
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-system-ingress-route-c8c92fb6
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.services.mkz.me`)
      middlewares:
        - name: traefik-forward-auth
          namespace: traefik-forward-auth
      services:
        - kind: Service
          name: longhorn-frontend
          port: 80
  tls:
    secretName: secret-tls-www
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-backups
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 45 6 * * *
  groups:
    - default
  labels:
    job: daily-backup
  retain: 3
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-backups-disabled
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 5 31 2 *
  groups:
    - disabled
  labels:
    job: daily-backup
  retain: 3
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-snapshots
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 15 1,7,13,19 * * *
  groups:
    - default
  labels:
    job: multiple-snapshot
  retain: 1
  task: snapshot
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-snapshots-disabled
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 5 31 2 *
  groups:
    - disabled
  labels:
    job: multiple-snapshot
  retain: 1
  task: snapshot
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-snapshots-daily
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 5 31 2 *
  groups:
    - daily
  labels:
    job: multiple-daily
  retain: 1
  task: snapshot
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: longhorn-system-sm-c8c03c02
  namespace: longhorn-system
spec:
  endpoints:
    - port: manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  selector:
    matchLabels:
      app: longhorn-manager
