apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://mariadb-operator.github.io/mariadb-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-operator-helm-val-mariadb-operator-c8e0449f
  namespace: mariadb-operator
data:
  values.yaml: |
    # https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/values.yaml

    metrics:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 713890c4965a6432ee1e6274169a04936d9e7773e939895c6aa38925d82d312b
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      version: 0.28.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: mariadb-operator-helm-val-mariadb-operator-c8e0449f
      valuesKey: values.yaml
