apiVersion: v1
kind: Namespace
metadata:
  name: memos
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: memos
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: memos-es-postgres-c87059cc
  namespace: memos
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/memos/postgres
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: postgres
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memos
    spec:
      containers:
        - env:
            - name: MEMOS_DRIVER
              value: postgres
            - name: MEMOS_PORT
              value: "5230"
            - name: MEMOS_DSN
              valueFrom:
                secretKeyRef:
                  key: dsn
                  name: postgres
          image: neosmemo/memos:0.22.2
          name: memos
          volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
spec:
  ports:
    - name: http
      port: 5230
  selector:
    app.kubernetes.io/name: memos
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: memos
  namespace: memos
spec:
  ingressClassName: traefik
  rules:
    - host: memos.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: memos
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - memos.services.mkz.me
      secretName: secret-tls-www
