apiVersion: v1
kind: Namespace
metadata:
  name: microbin
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: microbin
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microbin-es-admin-c84c97a1
  namespace: microbin
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/microbin/admin
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: admin
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: microbin
  name: microbin-microbin-svc-c887b9e1
  namespace: microbin
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: microbin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microbin-microbin-sts-c880e7dd
  namespace: microbin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microbin
  serviceName: microbin-microbin-svc-c887b9e1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microbin
    spec:
      containers:
        - env:
            - name: MICROBIN_LIST_SERVER
              value: "FALSE"
            - name: MICROBIN_ENABLE_BURN_AFTER
              value: "TRUE"
            - name: MICROBIN_GC_DAYS
              value: "0"
            - name: MICROBIN_PRIVATE
              value: "TRUE"
            - name: MICROBIN_ENCRYPTION_CLIENT_SIDE
              value: "FALSE"
            - name: MICROBIN_ENCRYPTION_SERVER_SIDE
              value: "TRUE"
            - name: MICROBIN_WIDE
              value: "TRUE"
            - name: MICROBIN_PUBLIC_PATH
              value: https://bin.iop.cx/
            - name: MICROBIN_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: admin
            - name: MICROBIN_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: admin
          image: ghcr.io/zhaobenny/microbin:latest
          name: microbin
          volumeMounts:
            - mountPath: /app/microbin_data
              name: micro-bin
      volumes: []
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: microbin
        name: micro-bin
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: microbin-ingress-c851ab8d
  namespace: microbin
spec:
  ingressClassName: traefik
  rules:
    - host: bin.iop.cx
      http:
        paths:
          - backend:
              service:
                name: microbin-microbin-svc-c887b9e1
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - bin.iop.cx
      secretName: secret-tls-www
