apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: minio
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-es-minio-tenant-c83a7f37
  namespace: minio
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/minio/minio-tenant
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: minio-tenant
    template:
      engineVersion: v2
      type: Opaque
