apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://operator.min.io/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-operator-es-root-c8c61a9b
  namespace: minio-operator
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/minio-operator/root
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: root
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-operator-es-minio-tenant-c8bf83d7
  namespace: minio-operator
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/minio-operator/minio-tenant
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: minio-tenant
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |-
    # https://github.com/minio/operator/blob/master/helm/operator/values.yaml
    operator:
      env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: username
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password


    # https://github.com/minio/operator/blob/master/helm/tenant/values.yaml
    tenants:
      - name: minio
        pools:
          - servers: 4
            name: pool
            volumesPerServer: 2
            storageClassName: longhorn-crypto-global
        metrics:
          enabled: true

    # Warning: The HR was suspended
    # It requires some secrets. See https://github.com/minio/operator/issues/856
metadata:
  name: minio-operator-helm-values-c8582209
  namespace: minio-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 4e01076316992a36be0422d5e671e93760a6d73b39661bc088a9e868706490bb
  name: minio-operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: 4.3.7
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: minio-operator-helm-values-c8582209
      valuesKey: values.yaml
