apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: minio-operator
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://operator.min.io/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-operator-es-root-c8c61a9b
  namespace: minio-operator
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/minio-operator/root
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: root
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-operator-helm-val-operator-c8f58c16
  namespace: minio-operator
data:
  values.yaml: |
    # Warning: The file is called `minio-operator` but this is minio's operator that is installed, not `minio-operator` which seems to be deprecated.

    # https://github.com/minio/operator/blob/master/helm/operator/values.yaml
    operator:
      env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: root
              key: username
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root
              key: password

    console:
      ingress:
        enabled: true
        host: minio-console.services.mkz.me
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/redirect-entry-point: https
          traefik.ingress.kubernetes.io/redirect-permanent: "true"
          traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
        ingressClassName: traefik
        tls:
          - hosts:
            - minio-console.services.mkz.me
            secretName: secret-tls-www
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 18d125335e0288a4bf81ce6cffbc607a31293cde93f6343ef1c6994f7276c88a
  name: operator
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: 5.0.12
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: minio-operator-helm-val-operator-c8f58c16
      valuesKey: values.yaml
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: console-sa
  name: console-sa-secret
  namespace: minio-operator
type: kubernetes.io/service-account-token
