apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-helm-val-nats-c8e3a028
  namespace: nats
data:
  values.yaml: |+
    # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

    config:
      jetstream:
        enabled: true

        memStorage:
          enabled: true
          size: "2Gi"

        fileStorage:
          enabled: true
          size: "10Gi"
          storageClassName: "longhorn-crypto-global"

    exporter:
      enabled: true
      serviceMonitor:
        enabled: true

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 122cb0936ba3bc95b8db5b56a9e8b2357024c14df6f3739520da3a36d5518dab
  name: nats
  namespace: nats
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: 1.1.11
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: nats-helm-val-nats-c8e3a028
      valuesKey: values.yaml
