apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

    nats:
      jetstream:
        enabled: true

        memStorage:
          enabled: true
          size: "2Gi"

        fileStorage:
          enabled: true
          size: "10Gi"
          storageClassName: "longhorn-crypto-global"

      externalAccess: true
metadata:
  name: nats-helm-values-c8d24546
  namespace: nats
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: e07573471b9f7dd66764e7b8f13974000eb4ae45d0c2a918f5465526f0f15767
  name: nats
  namespace: nats
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: 0.19.9
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: nats-helm-values-c8d24546
      valuesKey: values.yaml
