apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-helm-val-nats-c8e3a028
  namespace: nats
data:
  values.yaml: |
    # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

    config:
      jetstream:
        enabled: true

        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: "32Gi"
            storageClassName: "longhorn-crypto-global"

      monitor:
        enabled: true
        port: 8222

    promExporter:
      enabled: true
      podMonitor:
        enabled: true

    service:
      enabled: true
      ports:
        nats:
          enabled: true
        leafnodes:
          enabled: true
        websocket:
          enabled: true
        mqtt:
          enabled: true
        cluster:
          enabled: false
        gateway:
          enabled: false
        monitor:
          enabled: true
        profiling:
          enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: fd3edd3161521b555e9e7d8ea7eaefeb42278c02bbd99bcb1a4498a1bef4a153
  name: nats
  namespace: nats
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: 2.12.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: nats-helm-val-nats-c8e3a028
      valuesKey: values.yaml
