apiVersion: v1
kind: Namespace
metadata:
  name: paperless-ngx
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: paperless-ngx
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
  name: paperless-ngx-service-c8ebcf27
  namespace: paperless-ngx
spec:
  ports:
    - name: http
      port: 6789
  selector:
    app.kubernetes.io/component: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paperless-ngx-statefulset-c8860380
  namespace: paperless-ngx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  serviceName: paperless-ngx-service-c8ebcf27
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      containers:
        - command:
            - redis-server --save 60 1 --loglevel warning
          env: []
          image: redis:7.0.9
          name: redis
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/component: redis
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx-svc-redis-c8eaca31
  namespace: paperless-ngx
spec:
  ports:
    - name: redis
      port: 6879
  selector:
    app.kubernetes.io/component: redis
