apiVersion: v1
kind: Namespace
metadata:
  name: promtail
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: promtail
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-helm-val-promtail-c865fd71
  namespace: promtail
data:
  values.yaml: |
    # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml

    config:
      clients:
        - url: http://loki-gateway.loki/loki/api/v1/push

    serviceMonitor:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: a1c6a8dfe32630336e9f04699bc3f6e455b81a2ca15fb1d91c879bae5fef80f0
  name: promtail
  namespace: promtail
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.11.2
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: promtail-helm-val-promtail-c865fd71
      valuesKey: values.yaml
