apiVersion: v1
kind: Namespace
metadata:
  name: promtail
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: promtail
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-helm-val-promtail-c865fd71
  namespace: promtail
data:
  values.yaml: |
    # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml

    config:
      clients:
        - url: http://loki-gateway.loki/loki/api/v1/push

    service:
      enabled: false
      label:
        dummy-label: due-to-broken-chart

    serviceMonitor:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 1f57e927592cc503363c149f604f76366fcd74ca8b24e14e9d103a2bbc107368
  name: promtail
  namespace: promtail
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.16.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: promtail-helm-val-promtail-c865fd71
      valuesKey: values.yaml
