apiVersion: v1
kind: Namespace
metadata:
  name: redmine
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: redmine
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redmine-es-mariadb-c80c3c1f
  namespace: redmine
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/redmine/mariadb
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: mariadb
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redmine
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-helm-val-redmine-c85ec338
  namespace: redmine
data:
  values.yaml: |-
    # https://github.com/bitnami/charts/blob/main/bitnami/redmine/values.yaml

    mariadb:
      enabled: false

    postgresql:
      enabled: false

    externalDatabase:
      host: mariadb.mariadb
      port: 3306
      user: redmine
      database: redmine
      existingSecret: mariadb
      existingSecretPasswordKey: password

    persistence:
      enabled: true
      storageClass: longhorn-crypto-global
      size: 16Gi

    ingress:
      enabled: true
      hostname: redmine.services.mkz.me
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

    redmineUsername: redmine

    image:
      debug: true

    service:
      type: ClusterIP
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 678dc050b9737810f59e7b00ed813812a2298b4fba60e6efe2495d0445852f4e
  name: redmine
  namespace: redmine
spec:
  chart:
    spec:
      chart: redmine
      sourceRef:
        kind: HelmRepository
        name: redmine
        namespace: flux-system
      version: 27.1.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: redmine-helm-val-redmine-c85ec338
      valuesKey: values.yaml
