apiVersion: v1
kind: Namespace
metadata:
  name: scylla
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  agentVersion: 3.2.6
  datacenter:
    name: eu-west-1
    racks:
      - members: 3
        name: eu-west-1a
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "0.25"
            memory: 2Gi
        storage:
          capacity: 32Gi
          storageClassName: longhorn-crypto-global
  developerMode: true
  repository: scylladb/scylla
  version: 5.4.4
