apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sealed-secrets-helm-val-sealed-secrets-c8cfe4e4
  namespace: sealed-secrets
data:
  values.yaml: |
    # https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml

    namespace: sealed-secrets

    metrics:
      serviceMonitor:
        enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 406df4f5eaea05fe99aedc108d59e47a56f75f4dd55b632e45a0ffc014dc089a
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: 2.16.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values:
    fullnameOverride: sealed-secrets-controller
  valuesFrom:
    - kind: ConfigMap
      name: sealed-secrets-helm-val-sealed-secrets-c8cfe4e4
      valuesKey: values.yaml
