apiVersion: v1
kind: Namespace
metadata:
  name: send
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: send
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: send-es-minio-c8ae09d0
  namespace: send
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/send/minio
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: minio
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
  name: send-redis-svc-c8e30a3c
  namespace: send
spec:
  ports:
    - name: http
      port: 6379
  selector:
    app.kubernetes.io/component: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: send-redis-sts-c8957646
  namespace: send
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  serviceName: send-redis-svc-c8e30a3c
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      containers:
        - command:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          env: []
          image: redis:8.6.0
          name: redis
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 0
      volumes: []
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/component: redis
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-deploy-c8e3b68d
  namespace: send
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: send
  template:
    metadata:
      labels:
        app.kubernetes.io/component: send
    spec:
      containers:
        - env:
            - name: BASE_URL
              value: https://send.services.mkz.me
            - name: REDIS_HOST
              value: send-redis-svc-c8e30a3c.send
            - name: S3_ENDPOINT
              value: https://minio-storage.services.mkz.me
            - name: S3_BUCKET
              value: send
            - name: S3_USE_PATH_STYLE_ENDPOINT
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_SECRET_KEY
                  name: minio
          image: registry.gitlab.com/timvisee/send:v3.4.27
          name: send
          volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: send-svc-c8d4a006
  namespace: send
spec:
  ports:
    - name: http
      port: 1443
  selector:
    app.kubernetes.io/component: send
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: send-ingress-c84bea81
  namespace: send
spec:
  ingressClassName: traefik
  rules:
    - host: send.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: send-svc-c8d4a006
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - send.services.mkz.me
      secretName: secret-tls-www
