apiVersion: v1
kind: Namespace
metadata:
  name: tekton-builds
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    build: k8s-home-tekton-cicd
  name: hello
  namespace: tekton-builds
spec:
  steps:
    - image: alpine
      name: echo
      script: |
        #!/bin/sh
        echo "Hello World"
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  labels:
    build: k8s-home-tekton-cicd
  name: hello-task-run
  namespace: tekton-builds
spec:
  taskRef:
    name: hello
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    build: k8s-home-tekton-cicd
  name: goodbye
  namespace: tekton-builds
spec:
  params:
    - name: username
      type: string
  steps:
    - image: ubuntu
      name: goodbye
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    build: k8s-home-tekton-cicd
  name: hello-goodbye
  namespace: tekton-builds
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello
      taskRef:
        name: hello
    - name: goodbye
      params:
        - name: username
          value: $(params.username)
      runAfter:
        - hello
      taskRef:
        name: goodbye
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    build: k8s-home-tekton-cicd
  name: hello-goodbye-run
  namespace: tekton-builds
spec:
  params:
    - name: username
      value: Tekton
  pipelineRef:
    name: hello-goodbye
