apiVersion: v1
kind: Namespace
metadata:
  name: tempo
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: tempo
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-helm-val-tempo-c8fe2297
  namespace: tempo
data:
  values.yaml: |
    # https://github.com/grafana/helm-charts/blob/main/charts/tempo/values.yaml

    replicas: 1

    tempo:
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal

    tempoQuery:
      enabled: true
      repository: grafana/tempo-query
      tag: 2.5.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 9fa4187a54054eb8cda76191bae768aa1cee934a64b26021bc8cf044f8ce54b5
  name: tempo
  namespace: tempo
spec:
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 1.18.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: tempo-helm-val-tempo-c8fe2297
      valuesKey: values.yaml
