apiVersion: v1
kind: Service
metadata:
  name: traefik-svc-c8020cda
  namespace: kube-system
spec:
  ports:
    - name: web
      port: 9000
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/app-root: /dashboard/
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
  name: traefik-ingress-c8bc65a0
  namespace: kube-system
spec:
  ingressClassName: traefik
  rules:
    - host: traefik.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: traefik-svc-c8020cda
                port:
                  name: web
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - traefik.services.mkz.me
      secretName: secret-tls-www
