apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aqua
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-helm-values-c80e8437
  namespace: trivy-system
data:
  values.yaml: |
    # https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml

    resources:
      requests:
        cpu: 200m
        memory: 6Gi
      limits:
        cpu: 1
        memory: 8Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 2051be7e62003502adad6afffc8426c9a321f4d7605a3509044d14b4400a3ed3
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      version: 0.12.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values:
    trivy.ignoreUnfixed: "true"
  valuesFrom:
    - kind: ConfigMap
      name: trivy-helm-values-c80e8437
      valuesKey: values.yaml
