apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aqua
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |
    # https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml

    resources:
      requests:
        cpu: 200m
        memory: 1024Mi
      limits:
        cpu: 1
        memory: 2Gi
metadata:
  name: trivy-helm-values-c80e8437
  namespace: trivy-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: f4dd9b2beb9dd7cbe0fb4fe56f309ef2ae0e43bb7447e4bc73048745e1b64cbb
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      version: 0.5.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values:
    trivy.ignoreUnfixed: "true"
  valuesFrom:
    - kind: ConfigMap
      name: trivy-helm-values-c80e8437
      valuesKey: values.yaml
