apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: aqua
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trivy-helm-val-trivy-operator-c88a521d
  namespace: trivy-system
data:
  values.yaml: |
    # https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml

    resources:
      requests:
        cpu: 200m
        memory: 6Gi
      limits:
        cpu: 1
        memory: 8Gi

    trivy:
      extraEnvVars:
        OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "1"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: 653e951ed9b075f7c0cd8bed32f39120eb29576ffb5ffca32f27368dd5b6f792
  name: trivy-operator
  namespace: trivy-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      version: 0.14.1
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values:
    trivy.ignoreUnfixed: "true"
  valuesFrom:
    - kind: ConfigMap
      name: trivy-helm-val-trivy-operator-c88a521d
      valuesKey: values.yaml
