apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden-vaultwarden-svc-c829752e
  namespace: vaultwarden
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: vaultwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden-vaultwarden-sts-c8d72f35
  namespace: vaultwarden
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  serviceName: vaultwarden-vaultwarden-svc-c829752e
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
    spec:
      containers:
        - env: []
          image: vaultwarden/server:1.30.3
          name: vaultwarden
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: vaultwarden
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc-c80e18c0
  namespace: vaultwarden
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: vaultwarden
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: vaultwarden-ingress-c802bdba
  namespace: vaultwarden
spec:
  ingressClassName: traefik
  rules:
    - host: vaultwarden.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: vaultwarden-svc-c80e18c0
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.services.mkz.me
      secretName: secret-tls-www
