apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: vaultwarden
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-es-admin-c8233001
  namespace: vaultwarden
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/vaultwarden/admin
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: admin
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-es-mail-c8dc63de
  namespace: vaultwarden
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/vaultwarden/mail
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: mail
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden-vaultwarden-svc-c829752e
  namespace: vaultwarden
spec:
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/name: vaultwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden-vaultwarden-sts-c8d72f35
  namespace: vaultwarden
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  serviceName: vaultwarden-vaultwarden-svc-c829752e
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: https://vaultwarden.services.mkz.me
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: admin
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  key: hostname
                  name: mail
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mail
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mail
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_SECURITY
              value: starttls
            - name: SMTP_FROM
              value: vaultwarden@mkz.me
          image: vaultwarden/server:1.37.3
          name: vaultwarden
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        fsGroup: 0
      volumes: []
  volumeClaimTemplates:
    - metadata:
        labels:
          app.kubernetes.io/name: vaultwarden
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-crypto-global
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: vaultwarden-ingress-c802bdba
  namespace: vaultwarden
spec:
  ingressClassName: traefik
  rules:
    - host: vaultwarden.services.mkz.me
      http:
        paths:
          - backend:
              service:
                name: vaultwarden-vaultwarden-svc-c829752e
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - vaultwarden.services.mkz.me
      secretName: secret-tls-www
