apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: v1
kind: ConfigMap
data:
  values.yaml: |-
    server:
      logLevel: "debug"
metadata:
  name: vault-helm-values-c8b20a1d
  namespace: vault
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    configMapHash: fbab266e3da9b1526a5bf020d8015a22466aa4a5161e0b8c0dad9158c5712c2c
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: 0.22.0
  install:
    createNamespace: false
    skipCRDs: false
  interval: 1m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: vault-helm-values-c8b20a1d
      valuesKey: values.yaml
