apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-vault
  namespace: vikunja
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
      path: secret
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-es-postgresql-c8ccc3dd
  namespace: vikunja
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: secret/namespaces/vikunja/postgresql
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: secretstore-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    immutable: false
    name: postgresql
    template:
      engineVersion: v2
      type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://kolaente.dev/vikunja
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vikunja-helm-val-vikunja-c8cd38b1
  namespace: vikunja
data:
  values.yaml: |
    ## This chart relies on the common library chart from bjw-s
    ## You can find it and the values you can provide and modify, at https://github.com/bjw-s/helm-charts/tree/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common
    ## Here's the link to the values.yaml file: https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml
    ## Refer there for more detail about the supported values.
    ## Any values that you find in the above `values.yaml` can be provided to this chart and are then rendered.

    image:
      tag: 0.21.0

    ######################
    # VIKUNJA COMPONENTS #
    ######################
    # You can find the default values that this `values.yaml` overrides, in the comment at the top of this file.
    api:
      enabled: true
      image:
        repository: vikunja/api
        tag: 0.21.0
        pullPolicy: IfNotPresent
      persistence:
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
          mountPath: /app/vikunja/files
          storageClass: longhorn-crypto-global
      ingress:
        main:
          enabled: true
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: vikunja-backend.services.mkz.me
              paths:
                - path: "/api/v1"
          tls:
            - hosts:
              - vikunja-backend.services.mkz.me
              secretName: www-tls-crt

      configMaps:
        # See https://vikunja.io/docs/config-options/
        config:
          enabled: true
          data:
            config.yml: |
              # Vikunja needs to know the frontend URL for password reset emails.
              # So you might need to provide its value, if you're not using an ingress.
              service:
                enableregistration: false
                frontendUrl: https://vikunja.services.mkz.me

              log:
                level: DEBUG

              mailer:
                enabled: false

      env:
        # To utilize a secret in the environment variables, you can do something like the following: https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml#L141-L145
        # You could also use MySQL or SQLite, but we recommend PostgreSQL.
        # https://vikunja.io/docs/config-options/#type
        VIKUNJA_DATABASE_TYPE: "postgres"
        VIKUNJA_DATABASE_NAME: "vikunja"
        VIKUNJA_DATABASE_HOST: postgres-instance.postgres
        VIKUNJA_DATABASE_USER:
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: username
        VIKUNJA_DATABASE_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        

    frontend:
      enabled: true
      # You can add any of the top-level keys in the common chart's `values.yaml` to override them here.
      # For example, this values.yaml file overrides the image values, located here:
      # https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml#L63-L69
      image:
        repository: vikunja/frontend
        tag: 0.21.0
        pullPolicy: IfNotPresent
      # You can use either a `service` or an `ingress` to interact with Vikunja's frontend.
      # `Ingress` is the recommended option, but you can still set the `service` to
      # `LoadBalancer` or another service type.
      # https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml#L294-L354
      service:
        main:
          type: ClusterIP

      # https://github.com/bjw-s/helm-charts/blob/a081de53024d8328d1ae9ff7e4f6bc500b0f3a29/charts/library/common/values.yaml#L393-L436
      ingress:
        main:
          enabled: true
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            # This is just an example. You should change this to your own domain.
            - host: vikunja.services.mkz.me
              paths:
                - path: "/"
          tls:
            - hosts:
              - vikunja.services.mkz.me
              secretName: backend-tls-crt

      env:
        VIKUNJA_API_URL: https://vikunja-backend.services.mkz.me/api/v1

    ##########################
    # END VIKUNJA COMPONENTS #
    ##########################

    # Optional Dependencies

    postgresql:
      enabled: false


    redis:
      enabled: false

    typesense:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    configMapHash: f0d30986a9f99f6aa88053bf5ea48d558736df10fff14eaeed840436bbdfad74
  name: vikunja
  namespace: vikunja
spec:
  chart:
    spec:
      chart: vikunja
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux-system
      version: 0.4.3
  install:
    createNamespace: false
    skipCRDs: false
  interval: 10m0s
  timeout: 5m0s
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: vikunja-helm-val-vikunja-c8cd38b1
      valuesKey: values.yaml
