# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml

replicas: 1

serviceMonitor:
  enabled: true

  selfMonitor:
    enabled: true

  targets:
  - name: hey
    url: https://hey.mkz.me/
    interval: 10s
    module: http_2xx
