# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml

# The secrets to read & to put in dex pods
envFrom:
  - name: GITEA_CLIENT_ID
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/gitea
      key: client_id
  - name: GITEA_CLIENT_SECRET
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/gitea
      key: client_secret
  - name: GITEA_BASEURL
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/gitea
      key: base_url
  - name: STATIC_ADMIN_EMAIL
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/static-admin
      key: email
  - name: STATIC_ADMIN_HASH
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/static-admin
      key: hash
  - name: STATIC_ADMIN_USERNAME
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/static-admin
      key: username
  - name: STATIC_ADMIN_UUID
    valueFrom:
      secretKeyRef: secrets/namespaces/dex-idp/static-admin
      key: user_id

# The configuration is now in the secret
configSecret:
  create: false
  name: "dex-config"

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"

  hosts:
    - host: dex.services.mkz.me
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - dex.services.mkz.me
      secretName: dex-cert-tls

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
