# https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml

# The secrets to read & to put in dex pods
envVars:
  - name: "GITEA_CLIENT_ID"
    valueFrom:
      secretKeyRef:
        name: "gitea"
        key: "client_id"
  - name: "GITEA_CLIENT_SECRET"
    valueFrom:
      secretKeyRef:
        name: "gitea"
        key: "client_secret"
  - name: "GITEA_BASEURL"
    valueFrom:
      secretKeyRef:
        name: "gitea"
        key: "base_url"
  - name: "STATIC_ADMIN_EMAIL"
    valueFrom:
      secretKeyRef:
        name: "static-admin"
        key: "email"
  - name: "STATIC_ADMIN_HASH"
    valueFrom:
      secretKeyRef:
        name: "static-admin"
        key: "hash"
  - name: "STATIC_ADMIN_USERNAME"
    valueFrom:
      secretKeyRef:
        name: "static-admin"
        key: "username"
  - name: "STATIC_ADMIN_UUID"
    valueFrom:
      secretKeyRef:
        name: "static-admin"
        key: "user_id"
# Grafana
  - name: "GRAFANA_LOGIN_URL"
    valueFrom:
      secretKeyRef:
        name: "grafana-oidc-client"
        key: "login_url"
  - name: "GRAFANA_CLIENT_ID"
    valueFrom:
      secretKeyRef:
        name: "grafana-oidc-client"
        key: "client_id"
  - name: "GRAFANA_CLIENT_SECRET"
    valueFrom:
      secretKeyRef:
        name: "grafana-oidc-client"
        key: "client_secret"
# traefik-forward-auth
  - name: "TRAEFIK_FORWARD_AUTH_REDIRECT_URI"
    valueFrom:
      secretKeyRef:
        name: "traefik-forward-auth-oidc"
        key: "redirect_uri"
  - name: "TRAEFIK_FORWARD_AUTH_CLIENT_ID"
    valueFrom:
      secretKeyRef:
        name: "traefik-forward-auth-oidc"
        key: "client_id"
  - name: "TRAEFIK_FORWARD_AUTH_CLIENT_SECRET"
    valueFrom:
      secretKeyRef:
        name: "traefik-forward-auth-oidc"
        key: "client_secret"
# postgresql
  - name: "POSTGRESQL_USERNAME"
    valueFrom:
      secretKeyRef:
        name: "postgresql"
        key: "username"
  - name: "POSTGRESQL_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: "postgresql"
        key: "password"


# The configuration is now in the secret
configSecret:
  create: false
  name: "dex-config"

ingress:
  enabled: true

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
  
  className: traefik

  hosts:
    - host: dex.services.mkz.me
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - dex.services.mkz.me
      secretName: dex-cert-tls

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
