# See https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml
# Note: Modifying this file makes it mandatory to restart the deployment!

issuer: https://dex.services.mkz.me

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false

connectors:
- type: gitea
  id: gitea
  name: Gitea
  config:
    clientID: "{{ .Env.GITEA_CLIENT_ID }}"
    clientSecret: "{{ .Env.GITEA_CLIENT_SECRET }}"
    redirectURI: https://dex.services.mkz.me/callback
    baseURL: "{{ .Env.GITEA_BASEURL }}"

storage:
  type: memory

staticClients:
- id: grafana
  redirectURIs:
  - {{ .Env.GRAFANA_LOGIN_URL }}
  name: "{{ .Env.GRAFANA_CLIENT_ID }}"
  secret: "{{ .Env.GRAFANA_CLIENT_SECRET }}"
- id: traefik-forward-auth
  redirectURIs:
  - {{ .Env.TRAEFIK_FORWARD_AUTH_REDIRECT_URI }}
  name: "{{ .Env.TRAEFIK_FORWARD_AUTH_CLIENT_ID }}"
  secret: "{{ .Env.TRAEFIK_FORWARD_AUTH_CLIENT_SECRET }}"

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

enablePasswordDB: false

# staticPasswords:
# - email: "{{ .Env.STATIC_ADMIN_EMAIL }}"
#   # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
#   hash: "{{ .Env.STATIC_ADMIN_HASH }}"
#   username: "{{ .Env.STATIC_ADMIN_USERNAME }}"
#   userID: "{{ .Env.STATIC_ADMIN_UUID }}"
