# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml

allInOne:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - jaeger.services.mkz.me
    ingressClassName: traefik
    tls:
    - secretName: tls-jaeger-cert
      hosts:
      - jaeger.services.mkz.me
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
agent:
  enabled: false
collector:
  enabled: false
ingester:
  enabled: false
query:
  enabled: false

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

storage:
  type: elasticsearch
  elasticsearch:
    host: opensearch-cluster-master.opensearch
    port: 9200
