prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi

alertmanager:
  alertmanagerSpec:
    replicas: 2
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 512Mi

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/redirect-entry-point: "https"
      traefik.ingress.kubernetes.io/redirect-permanent: "true"

    hosts: ["grafana.services.mkz.me"]
    tls:
    - secretName: tls-grafana-cert
      hosts:
      - grafana.services.mkz.me

  admin:
    existingSecret: grafana-secret
    userKey: user
    passwordKey: password

  env:
    GF_DATABASE_TYPE: postgres
    GF_DATABASE_NAME: grafana
    GF_DATABASE_HOST: postgres-monitoring
    GF_DATABASE_SSL_MODE: require

  envValueFrom:
    GF_DATABASE_USER:
      secretKeyRef:
        name: grafana.postgres-monitoring.credentials.postgresql.acid.zalan.do
        key: username
    GF_DATABASE_PASSWORD:
      secretKeyRef:
        name: grafana.postgres-monitoring.credentials.postgresql.acid.zalan.do
        key: password
