grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/redirect-entry-point: "https"
      traefik.ingress.kubernetes.io/redirect-permanent: "true"

    hosts: ["grafana.services.mkz.me"]
    tls:
    - secretName: tls-grafana-cert
      hosts:
      - grafana.services.mkz.me
  admin:
    existingSecret: grafana-secret
    userKey: user
    passwordKey: password
