# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: 2024-01-01
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
  storage:
    type: filesystem
    bucketNames:
      chunks: loki_chunks
      ruler: loki_ruler
      admin: loki_admin

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 10Gi
    storageClass: local-path

read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

monitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: false

# gateway:
#   service:
#     labels:
#       prometheus.io/service-monitor: "false"
