# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      s3: null
      endpoint: https://minio-storage-hl.minio.svc.cluster.local:9000
      region: null
      secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
      accessKeyId: ${MINIO_ACCESS_KEY_ID}
      s3ForcePathStyle: true
      insecure: true
      http_config: {}

write:
  extraArgs:
  - --config.expand-env=true

  extraEnv:
  - name: MINIO_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio
        key: access_key_id
  - name: MINIO_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio
        key: secret_access_key

  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 10Gi
    storageClass: longhorn-crypto-global

read:
  extraArgs:
  - --config.expand-env=true

  extraEnv:
  - name: MINIO_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio
        key: access_key_id
  - name: MINIO_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio
        key: secret_access_key

  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 10Gi
    storageClass: longhorn-crypto-global

backend:
  extraArgs:
  - --config.expand-env=true

  extraEnv:
  - name: MINIO_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: minio
        key: access_key_id
  - name: MINIO_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio
        key: secret_access_key

  persistence:
    enableStatefulSetAutoDeletePVC: false
    size: 10Gi
    storageClass: longhorn-crypto-global

monitoring:
  lokiCanary:
    enabled: false

test:
  enabled: false
