# Warning: The file is called `minio-operator` but this is minio's operator that is installed, not `minio-operator` which seems to be deprecated.

# https://github.com/minio/operator/blob/master/helm/operator/values.yaml
operator:
  env:
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: root
          key: username
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: root
          key: password

console:
  ingress:
    enabled: true
    host: minio-console.services.mkz.me
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
    tls:
      - hosts:
        - minio-console.services.mkz.me
        secretName: secret-tls-www
