# Warning: The file is called `minio-operator` but this is minio's operator that is installed, not `minio-operator` which seems to be deprecated.

# Manual upgrade:
# helm upgrade minio-operator minio/minio-operator -n minio-operator --values ~/dev/k8s-home/configs/minio-operator.yaml

# https://github.com/minio/operator/blob/master/helm/operator/values.yaml
operator:
  env:
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: root
          key: username
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: root
          key: password

# It requires some secrets. See https://github.com/minio/operator/issues/856