# https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

config:
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "2Gi"

    fileStorage:
      enabled: true
      size: "10Gi"
      storageClassName: "longhorn-crypto-global"

  monitor:
    enabled: true
    port: 8222

promExporter:
  enabled: true
  podMonitor:
    enabled: true

service:
  enabled: true
  ports:
    nats:
      enabled: true
    leafnodes:
      enabled: true
    websocket:
      enabled: true
    mqtt:
      enabled: true
    cluster:
      enabled: false
    gateway:
      enabled: false
    monitor:
      enabled: true
    profiling:
      enabled: false
