# https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

config:
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "2Gi"

    fileStorage:
      enabled: true
      size: "10Gi"
      storageClassName: "longhorn-crypto-global"

exporter:
  enabled: true
  serviceMonitor:
    enabled: true

