# https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml

nats:
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "2Gi"

    fileStorage:
      enabled: true
      size: "10Gi"
      storageClassName: "longhorn-crypto-global"

  # Enabling this requires to bump nats-boot-config to 0.9.3
  # and to add to nodes the following label:
  # nats.io/node-external-ip
  externalAccess: false

exporter:
  enabled: true
  serviceMonitor:
    enabled: true

