# https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml

config:
  clients:
    - url: http://loki-gateway.loki/loki/api/v1/push

service:
  enabled: false
  labels:
    dummy-label: due-to-broken-chart

serviceMonitor:
  enabled: true
