# https://github.com/temporalio/helm-charts/blob/master/charts/temporal/values.yaml

server:
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgres-instance.postgres
          port: 5432
          user: temporal2
          database: temporal2
          maxConns: 20
          maxConnLifetime: "1h"
          existingSecret: postgresql2
      visibility:
        driver: "sql"
        sql:
          driver: "postgres12"
          host: postgres-instance.postgres
          port: 5432
          user: temporal_visibility2
          database: temporal_visibility2
          maxConns: 20
          maxConnLifetime: "1h"
          existingSecret: postgresql-visibility2

web:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - temporal.services.mkz.me
    tls:
      - secretName: temporal-tls
        hosts:
          - temporal.services.mkz.me

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: false
  update:
    enabled: false
