# https://github.com/temporalio/helm-charts/blob/master/charts/temporal/values.yaml

server:
  config:
    persistence:
      datastores:
        default:
          driver: "sql"
          sql:
            pluginName: "postgres12"
            connectAddr: "postgres-instance.postgres:5432"
            connectProtocol: tcp
            user: temporal2
            databaseName: temporal2
            maxConns: 20
            maxConnLifetime: "1h"
            existingSecret: postgresql2
            createDatabase: false
            manageSchema: false
        visibility:
          driver: "sql"
          sql:
            pluginName: "postgres12"
            connectAddr: "postgres-instance.postgres:5432"
            connectProtocol: tcp
            user: temporal_visibility2
            databaseName: temporal_visibility2
            maxConns: 20
            maxConnLifetime: "1h"
            existingSecret: postgresql-visibility2
            createDatabase: false
            manageSchema: false

shims:
  dockerize: false # Disable if using Temporal 1.30+
  elasticsearchTool: false # Disable if using Temporal 1.30+

web:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth-traefik-forward-auth@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - temporal.services.mkz.me
    tls:
      - secretName: temporal-tls
        hosts:
          - temporal.services.mkz.me
