# https://github.com/aquasecurity/trivy/blob/main/helm/trivy/values.yaml

resources:
  requests:
    cpu: 200m
    memory: 6Gi
  limits:
    cpu: 1
    memory: 8Gi

trivy:
  extraEnvVars:
    OPERATOR_CONCURRENT_SCAN_JOBS_LIMIT: "1"
