# https://github.com/hashicorp/vault-helm/blob/main/values.yaml

server:
  logLevel: "debug"
  logFormat: "standard"

  dataStorage:
    enabled: true
    size: 1Gi
    mountPath: "/vault/data"
    storageClass: longhorn-crypto-global
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 1Gi
    mountPath: "/vault/audit"
    storageClass: longhorn-crypto-global
    accessMode: ReadWriteOnce

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"

    hosts:
      - host: vault.services.mkz.me
        paths: []

    tls:
      - secretName: vault-tls
        hosts:
          - vault.services.mkz.me

injector:
  logLevel: "debug"
  logFormat: "standard"

ui:
  enabled: true

serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true