# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

backupsEnabled: true
snapshotsEnabled: false
deployNodeAgent: true

nodeAgent:
  containerSecurityContext:
    privileged: true

metrics:
  serviceMonitor:
    enabled: true

configuration:
  uploaderType: kopia
  defaultVolumesToFsBackup: false
  backupStorageLocation:
    - provider: aws
      default: true
      bucket: velero
      config:
        region: garage
        s3Url: "http://moonstone.lan.mkz.me:3900"
        s3ForcePathStyle: true

credentials:
  existingSecret: garage-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

upgradeJobResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 1024Mi

kubectl:
  image:
    repository: public.ecr.aws/bitnami/kubectl
    tag: latest
