# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

backupsEnabled: true
snapshotsEnabled: false

metrics:
  serviceMonitor:
    enabled: true

configuration:
  backupStorageLocation:
    - provider: aws
      default: true
      bucket: k8s-backup
      prefix: velero-backup
      config:
        region: minio
        s3Url: "http://nas0.lan.mkz.me:9000"
        s3ForcePathStyle: true

credentials:
  existingSecret: nas0-minio

initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.1.0
  imagePullPolicy: IfNotPresent
  volumeMounts:
  - mountPath: /target
    name: plugins

upgradeJobResources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 1024Mi
